### ISSUE TITLE
Deprecated Property and Function

### ISSUE THREAD

**Issue by Firman95** [diegoazh/gmap-vue#10]
I found two deprecated errors while using the map and autocomplete:

`open_now is deprecated as of November 2019 and will be turned off in November 2020. Use the isOpen() function from a PlacesService.getDetails() result instead.`

and

`utc_offset is deprecated as of November 2019 and will beturned off in November 2020. Use utc_offset_minutes instead.`

**Comment by josegus** [comment]
Same here, I've migrated from the original repo to this one. Thanks for your contribution @diegoazh , hope you can fix this soon.

![image](https://user-images.githubusercontent.com/13947849/82522294-f322d500-9af6-11ea-84b8-32d303cb9514.png)

**Comment by diegoazh** [comment]
Thank you for reporting it 👍🏽

**Comment by davydnorris** [comment]
tapping this so the bot doesn't close it! Needs to be done

**Comment by diegoazh** [comment]
> tapping this so the bot doesn't close it! Needs to be done

I'm working on it 😄, on the weekend a will fix all closed issues by the bot 🤦🏻‍♂️ includes my issues 😅.

**Comment by diegoazh** [comment]
@Firman95, @josegus can you provide more information about this.
I found in all code base and I didn't find any place where we use `utc_offset` or `open_now` if you can help me with a more detailed explanation about what were you doing when this deprecation appears will be a great clue.
In the case of `utc_offset` deprecation warning, I saw when autocomplete inputs is used but, I think that it is a simple notification from Google maps API to notify the change to all users.
Please let me know if you catch something that I missed.

**Comment by davydnorris** [comment]
in that case, I would assume that Google will automatically fix their own call and we don't need to do anything.

**Comment by diegoazh** [comment]
Thanks for the explanation @BenThurber, I agree with @davydnorris. I think we can close this issue.

**Comment by sdevore** [comment]
So it seems that this issue is not resolved by waiting for updates to the api from google's part I am still seeing it, should be looked at again and perhaps specify the fields better?  or is there a problem with the google api being pined to an old version?

**Comment by diegoazh** [comment]
@sdevore I will take a look again.

**Comment by zSkalin** [comment]
I'm still seeing this too on version 1.5.0

**Comment by lombo75** [comment]
For me if I take out utc_offset_minutes from the fields array the error doesn't occur

**Comment by Pijuli** [comment]
Still here. It's a bit messy on the console but I've had no problem using it.
Could you take a look at it again? I can't seem to find what's the real problem... :/
