### ISSUE TITLE
Feature: autocomplete with minimun characters

### ISSUE THREAD

**Issue by Davids89** [diegoazh/gmap-vue#102]
**Is your feature request related to a problem? Please describe.**
To avoid multiple calls to the Google Places API, It would be nice a selector of minimum characters required before call the API. 

**Describe the solution you'd like**
I think that only is necessary to add a prop in `/components-implementation/autocomplete.js` and a validation [here](https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/components-implementation/autocomplete.js#L94).

**Describe alternatives you've considered**

**Additional context**
I could add it, but if it is usefull for more people.

**Comment by diegoazh** [comment]
@Davids89 thanks for your suggestion, I like this approach. 👍🏽

**Comment by BenPilliez** [comment]
Do you have any update for this ? If no, have you got a method to do that ?

**Comment by diegoazh** [comment]
I'm on it, right now.

**Comment by diegoazh** [comment]
I have good news on this topic, it is already solved by Google 🎉.
You can check this [answer on StackOverflow](https://stackoverflow.com/a/42011655/5302733) and comment #42 of November 26, on the page that it shares.
The Google team solves this problem using [session tokens](https://developers.google.com/maps/documentation/places/web-service/session-tokens), you can find the explanation on the link, also, in the autocomplete documentation they mention that session tokens are automatically used by the autocomplete widget, you can find that [here, on the tip alert](https://developers.google.com/maps/documentation/javascript/places-autocomplete#session_tokens).

I'll consider this issue solved and closed.

Regards.
