### ISSUE TITLE
Bug: Uncaught (in promise) TypeError: Cannot read property 'geocode' of undefined on mounted 

### ISSUE THREAD

**Issue by pechanxur** [diegoazh/gmap-vue#103]
**Describe the bug**
i need to geolocate the user in the mounted method of the component, im trying to use [this](https://diegoazh.github.io/gmap-vue/#lazy-loading) but i got the mentionend error

**To Reproduce**
1. Create an async function as mentioned in the docs
2. create this variable `let geocoder = this.google.maps.Geocoder();`
3. try to use it as ` geocoder.geocode({ location: latLng }, (results, status) => {if (status === this.google.maps.GeocoderStatus.OK) {   console.log(results[0]); }})`

**Expected behavior**
geocode the lat and Lng to the located user and get the data (street name and other data)

**Current behavior**
the mentionend errror

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Mac os Catalina latest 
 - Browser Chrome
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

## Versions

- Node:14.12.0
- NPM:6.14.8
- Yarn: 1.22.5

## Package manager

- [ ] NPM
- [x] Yarn

## Plugin version

- [x] 1.4.0
- [ ] 1.2.2
- [ ] 1.2.1
- [ ] 1.2.0
- [ ] 1.0.0

**Comment by pechanxur** [comment]
why its closed? here its the screenshot of my mounted method 


![Screen Shot 2020-09-28 at 15 10 11](https://user-images.githubusercontent.com/20100156/94481329-2825ef00-019d-11eb-8340-f5f16415e5d5.png)

**Comment by diegoazh** [comment]
@pechanxur thanks for report this bug, in a few minutes a will land a new release fixing this bug.

**Comment by diegoazh** [comment]
Can you try these changes?

```javascript
        async mounted() {
          if (this.show && Object.entries(this.editableProperty).length) {...
            this.publicacion.uuid = this.$uuid.v4();

            // the above code is the same to only await this promise because when it resolves returns to you the `window.google` object
            // const google = await this.$gmapApiPromiseLazy();
            await this.$gmapApiPromiseLazy();
            this.geolocate(); // I don't know what this function does but I feel that it should be after the google maps library loads
            let geocoder = google.maps.Geocoder();

            geocoder.geocode({ location: latLng }), (results, status) => {
              if (status === google.maps.GeocoderStatus.OK) { ... }
            }
          }
        }
```

Please let me know if this was helpful.
Regards.
