### ISSUE TITLE
Feature: Chrome does not understand autocomplete="off"

### ISSUE THREAD

**Issue by kevmorpain** [diegoazh/gmap-vue#104]
**Is your feature request related to a problem? Please describe.**
Sorry if it's not a feature request, but it's not really a bug from gmap-vue either.
I have the same problem discribed here: https://stackoverflow.com/q/12374442, Chrome does not remove its own autocomplete when autocomplete is set as "off". It's working perfectly on every browser but Chrome.

**Describe the solution you'd like**
There's two solutions I see:
- set autocomplete to a different name, maybe random characters, so that it is not saved in any browser
- make it a prop for the gmap-autocomplete component, so that developers can set it to whatever they want (and "off" by default for example)

What do you think?

**Describe alternatives you've considered**
Possible alternative would have been to set anything else just for chrome (like "new-password" which is never saved) but having an specific configuration just for one browser might be bad.

**Additional context**
-

**Comment by diegoazh** [comment]
@kevmorpain thanks for open this issue.
I think this situation is very interesting. Like you said before setting a configuration only for one browser maybe is not a good idea. I don't know what is the opinion of other users about this topic, at the moment I never hear this kind of needs from a user of the plugin but maybe is something to consider in some situations.

**Comment by diegoazh** [comment]
This behaviour is related to the navigator not to the plugin.
Related issue #94 (is something similar, the other face of the coin).
