### ISSUE TITLE
Bug: gmap autocomplete component restrictions not work dynamically

### ISSUE THREAD

**Issue by tingan** [diegoazh/gmap-vue#105]
Hi,
` componentRestrictions: {
                        country: 'nl'
                    }`
i have a dropdown list of country code, i need to dynamically change above restrictions to the selected country code. i used watch to watch the country selection change and dynamically reset the gmap autocomplete options to the selected country code, but it not work.

**Comment by diegoazh** [comment]
Please can you follow our issue template and explain with more details what you do and what you need to do and some code example? I will be waiting for the new issue 👍🏽

**Comment by diegoazh** [comment]
@tingan please test the new version 2.0.0 and let me know if the issue persists.
