### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ivaralink** [diegoazh/gmap-vue#111]
**Describe the bug**
vue.common.dev.js:630 [Vue warn]: Error in mounted hook (Promise/async): "InvalidValueError: Map: Expected mapDiv of type Element but was passed undefined."

**To Reproduce**
1. Go to the view where this component is loaded

**Expected behavior**
The map is show whithout erros

**Current behavior**
The Map is shown with this error

**Desktop (please complete the following information):**
 - OS: [linux]
 - Browser [chrome]
 - Version [e.g. 86]]

## Versions
- Node: 10
- NPM: 6.4.1

## Package manager
- [ ] NPM

## Plugin version
- 1.5

This is my vue Component:
`<template>
    <GmapMap
        ref="mapRef"
        :center="location"
        :zoom="15"
        map-type-id="roadmap"
        style="width: 100%; height: 100%"
        :options="{
           zoomControl: true,
           mapTypeControl: true,
           scaleControl: false,
           streetViewControl: false,
           rotateControl: false,
           fullscreenControl: true,
           disableDefaultUI: false
         }">
        <GmapMarker
            :position="location"
            :clickable="true"
            :draggable="false"
            @click="centerLocation"
        />

        <GmapCircle
            :center="location"
            :radius="accuracy"
            :visible="true"
            :options="{fillColor:'red',fillOpacity:0.3}"
        ></GmapCircle>
    </GmapMap>
</template>
<script>
import {gmapApi} from "gmap-vue";

export default {
    name: 'GoogleMapsMap',
    props: {
        selectedDevice: Object,
        hasValidGoogleLocation: Boolean
    },
    data: () => ({
        lat: null,
        lng: null,
        accuracy: null
    }),
    created() {
        this.lat = parseFloat(this.selectedDevice.sensor.latest_google_geo_location.lat)
        this.lng = parseFloat(this.selectedDevice.sensor.latest_google_geo_location.lng)
        this.accuracy = parseFloat(this.selectedDevice.sensor.latest_google_geo_location.accuracy)
    },
    mounted() {
        this.centerLocation()
    },
    computed: {
        google: gmapApi,
        location() {
            return {lat: this.lat, lng: this.lng}
        },
    },
    methods: {
        centerLocation() {
            this.$refs.mapRef.$mapPromise.then((map) => {
                map.panTo(this.location)
            })
        }
    }
}
</script>

<style scoped>

</style>
`

**Comment by diegoazh** [comment]
duplicate #115
