### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ivaralink** [diegoazh/gmap-vue#113]
**Describe the bug**
this error is thrown in the console:
> vue.common.dev.js:630 [Vue warn]: Error in mounted hook (Promise/async): "InvalidValueError: Map: Expected mapDiv of type Element but was passed undefined."

Everything loads as expected, but i want to know how to get rid of this error. I cannot find something in my code that triggers this error

**To Reproduce**
1. Go to the view where this component is loaded

**Expected behavior**
The map is shows whithout errors

**Current behavior**
The Map is shown with this error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [linux]
 - Browser [chrome]
 - Version [e.g. 86]]

**Smartphone (please complete the following information):**
 - Not relavent

**Additional context**
This vue component is running in Vue 2 and laravel

## Versions
- Node: 10
- NPM: 6.4.1

## Package manager
- NPM

## Plugin version
- 1.5

**Comment by diegoazh** [comment]
ducplicate #115 (bot error cause this duplications)
