### ISSUE TITLE
Bug: InvalidValueError: Map: Expected mapDiv of type Element but was passed undefined

### ISSUE THREAD

**Issue by ivaralink** [diegoazh/gmap-vue#115]
**Describe the bug**
this error is thrown in the console:
> vue.common.dev.js:630 [Vue warn]: Error in mounted hook (Promise/async): "InvalidValueError: Map: Expected mapDiv of type Element but was passed undefined."

Everything loads as expected, but i want to know how to get rid of this error. I cannot find something in my code that triggers this error

**To Reproduce**
1. Go to the view where this component is loaded

**Expected behavior**
The map shows whithout errors

**Current behavior**
The Map is shown with this error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome
 - Version: 86

**Smartphone (please complete the following information):**
Device: N/A
OS: N/A
Browser: N/A
Version: N/A

**Additional context**
This vue component is running in Vue 2 and laravel 8

## Versions
- Node:10.23.0
- NPM:6.14.8

## Package manager
- [x] NPM
- [ ] Yarn

## Plugin version
- [x] 1.5.x
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

```
<template>
    <GmapMap
        ref="mapRef"
        :center="location"
        :zoom="15"
        map-type-id="roadmap"
        style="width: 100%; height: 100%"
        :options="{
           zoomControl: true,
           mapTypeControl: true,
           scaleControl: false,
           streetViewControl: false,
           rotateControl: false,
           fullscreenControl: true,
           disableDefaultUI: false
         }"
    >
        <GmapMarker
            :position="location"
            :clickable="true"
            :draggable="false"
            @click="centerLocation"
        />

        <GmapCircle
            :center="location"
            :radius="accuracy"
            :visible="true"
            :options="{fillColor:'red',fillOpacity:0.3}"
        ></GmapCircle>
    </GmapMap>
</template>

<script>
import {gmapApi} from "gmap-vue";

export default {
    name: 'GoogleMapsMap',
    props: {
        selectedDevice: Object,
        hasValidGoogleLocation: Boolean
    },
    data: () => ({
        lat: null,
        lng: null,
        accuracy: null
    }),
    created() {
        this.lat = parseFloat(this.selectedDevice.sensor.latest_google_geo_location.lat)
        this.lng = parseFloat(this.selectedDevice.sensor.latest_google_geo_location.lng)
        this.accuracy = parseFloat(this.selectedDevice.sensor.latest_google_geo_location.accuracy)
    },
    mounted() {
        this.centerLocation()
    },
    computed: {
        google: gmapApi,
        location() {
            return {lat: this.lat, lng: this.lng}
        },
    },
    methods: {
        centerLocation() {
            this.$refs.mapRef.$mapPromise.then((map) => {
                map.panTo(this.location)
            })
        }
    }
}
</script>

<style scoped>

</style>
```

**Comment by ivaralink** [comment]
Can you enlighten me as to why this bug is cloed?

**Comment by dovca** [comment]
I had this same problem today. I am using gmap-vue in Nuxt and the reason for this error was most likely the nuxt page component being mounted twice incorrectly (mounted -> destroyed -> mounted). In the first mount, the element passed to `new google.maps.Map()` was indeed undefined.

**Solution**:
Remove `build: { splitChunks: { layout: true } }` from nuxt.config.js or set the layout key to `false`, which is default.
It might not help everyone, but I wanted to share how I solved this problem.

**Comment by diegoazh** [comment]
I will consider this issue resolved and close the issue. Thanks @dovca  for your answer and @ivaralink for open this issue.
