### ISSUE TITLE
Bug: Typo in doc for polygon path_changed

### ISSUE THREAD

**Issue by mlereste** [diegoazh/gmap-vue#116]
**Describe the bug**

Hello! Thanks for this awesome plugin! :)

I think there is a small typo in the examples documentation for polygon simple and advanced: 
https://diegoazh.github.io/gmap-vue/examples/polygon-simple.html#live-example
https://diegoazh.github.io/gmap-vue/examples/polygon-advanced.html#live-example

In the `@path_changed` event

**To Reproduce**

N/A

**Expected behavior**

The following line:

`<gmap-polygon :paths="paths" :editable="true" @paths_changed="updateEdited($event)"></gmap-polygon>`

Should be:

`<gmap-polygon :paths="paths" :editable="true" @path _changed="updateEdited($event)"></gmap-polygon>`

`@paths_changed` => `@path _changed`

Based on the emited event:

https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/components/polygon.js#L138

**Current behavior**

N/A

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

If someone can confirme, I can submit a PR with a quick fix for this :)

Have a nice day!

## Versions

- Node: 12
- NPM: 6.14
- Yarn: 1.22

## Package manager

- [ ] NPM
- [x] Yarn

## Plugin version

- [x] 1.5.x
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by mlereste** [comment]
Is there a way to reopen issue once the template was fixed?

**Comment by diegoazh** [comment]
@mlereste can send a PR to fix this typo? Thank you.

**Comment by diegoazh** [comment]
@mlereste sorry about the bot I think is fixed now

**Comment by diegoazh** [comment]
Solved, we use `paths_changed` at the end.
Thanks and regards.
