### ISSUE TITLE
Need help on: Show title on marker

### ISSUE THREAD

**Issue by kossa** [diegoazh/gmap-vue#117]
# What you try to do
I want to show some information when I click on marker

# What is the problem

Currently it does not show anything 

# What kind of things have you already treated
```
<GmapMarker
                .....
                :title="m.title"
                ...
            />
```

# Steps to reproduce

Try to add title in GmapMarker

## Os

- [x] Mac Os X

## Versions

- Node: 14.14
- NPM: 6.14

## Package manager

- [x] NPM

## Plugin version

- [x] 1.5.x

**Comment by eregnier** [comment]
Hey, you might use [this plugin](https://github.com/eregnier/vue2-gmap-custom-marker) to do something very custom, this is not the most performant solution, but it is very flexible.
Disclaimer : I did this plugin :smile:

**Comment by kossa** [comment]
Really I like it, please add it to : https://github.com/vuejs/awesome-vue#map

**Comment by diegoazh** [comment]
@kossa please test the new version 2.0.0 and reopen the issue if the problem persists.

**Comment by diegoazh** [comment]
In v2.0.3 you have that prop and other possible props for Markers ([API link](https://diegoazh.github.io/gmap-vue/code/components/marker-icon.html#props)).
