### ISSUE TITLE
autocomplete.vue component scopedSlots renders a span by default

### ISSUE THREAD

**Issue by Felixclement** [diegoazh/gmap-vue#12]
would it be possible to pass a "tag" prop to render other html node like a div per example
would look something like this

`<template>
  <component :is="tag" v-if="$scopedSlots['input']">
    <slot name="input" v-bind:attrs="$attrs" v-bind:listeners="$listeners" :ref="input"></slot>
  </component>
  <input v-else-if="!$scopedSlots['input']" ref="input" v-bind="$attrs" v-on="$listeners" />
</template>`

**Comment by diegoazh** [comment]
@Felixclement sorry, I regret the delay with you, but sorry I think that I miss something because I don't catch you. Please can you explain more, thank you.
Regards

**Comment by diegoazh** [comment]
@Felixclement I think you are trying to use scoped slots in the autocomplete component, that is supported for GmapVue, please read check the documentation [here](https://diegoazh.github.io/gmap-vue/examples/autocomplete.html#source-code) at the end, you can find an example of scoped slot.
I am going to close this issue, but if I wrong and you are trying something different please reopen it 👍🏽.
