### ISSUE TITLE
Doc typo: Adding your own components

### ISSUE THREAD

**Issue by matiasperrone** [diegoazh/gmap-vue#124]
Docs

In the page https://diegoazh.github.io/gmap-vue/#officially-supported-components the link in "source code for mapElementFactory" should be pointing to "https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/factories/map-element.js" instead of the current one, because it goes to a 404 page

**Comment by diegoazh** [comment]
@matiasperrone in the future follow our issue template please

**Comment by matiasperrone** [comment]
Where is this template or ISSUE_TEMPLATE.md?

**Comment by diegoazh** [comment]
duplicate #125
