### ISSUE TITLE
Bug: Doc correct link in "source code for mapElementFactory"

### ISSUE THREAD

**Issue by matiasperrone** [diegoazh/gmap-vue#125]
**Describe the bug**

In the page https://diegoazh.github.io/gmap-vue/#officially-supported-components the link in "source code for mapElementFactory" should be pointing to "https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/factories/map-element.js" instead of the current one, because it goes to a 404 page

**To Reproduce**
1. Enter to the page https://diegoazh.github.io/gmap-vue/#officially-supported-components
2. Click on 'source code for mapElementFactory'
3. 404 page of error

**Expected behavior**
Show the source code

**Current behavior**
Showing a 404 page of error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
Not necessary

## Versions

- Node: 000
- NPM:000
- Yarn:000

## Package manager

- [x] NPM
- [x] Yarn

## Plugin version

- [x] 1.4.x
- [x] 1.2.x
- [x] 1.0.x

**Comment by matiasperrone** [comment]
@diegoazh It is impossible to report a problem!

**Comment by diegoazh** [comment]
@matiasperrone why?

**Comment by matiasperrone** [comment]
@diegoazh because every time I report (following the template) an issue, it is closed by a bot.
Check #125 for instance.

**Comment by matiasperrone** [comment]
this one too...

**Comment by matiasperrone** [comment]
By the way I love this component!
Che the one I am maintaining as well: https://github.com/krystalcampioni/vue-hotel-datepicker

**Comment by diegoazh** [comment]
@matiasperrone I will check the bot configuration but, it will take me a few days, thanks for letting me know about this.

**Comment by matiasperrone** [comment]
ping

**Comment by diegoazh** [comment]
Solved, thank you for reporting it.
