### ISSUE TITLE
Bug: PlacesService undefined

### ISSUE THREAD

**Issue by momtboy** [diegoazh/gmap-vue#128]
**Describe the bug**
```
import { gmapApi } from 'gmap-vue'

const res = await this.$gmapApiPromiseLazy();
if(res) {
  this.gMapApi = gmapApi();
}

const map = await this.$refs.searchGmap.$mapPromise;
console.log(await this.gMapApi.maps.places.PlacesService(map))   /// return undefined
```

**Desktop (please complete the following information):**
 - OS: [e.g. win]
 - Browser [chrome]
 - Version [88.0.4315.4]

**Additional context**

## Versions

- Node:  v12.16.1
- NPM:   6.13.4

## Package manager

- 

- [x]  NPM

- [ ] Yarn

## Plugin version
- [x] 1.5.0
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
duplicate #129
