### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by momtboy** [diegoazh/gmap-vue#129]
**Describe the bug**
```
import { gmapApi } from 'gmap-vue'

const res = await this.$gmapApiPromiseLazy();
if(res) {
  this.gMapApi = gmapApi();
}

const map = await this.$refs.searchGmap.$mapPromise;
console.log(await this.gMapApi.maps.places.PlacesService(map))   /// return undefined

```

**To Reproduce**
N/A

**Expected behavior**
N/A

**Current behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [win64]
 - Browser [chrome]
 - Version [88.0.4315.4]

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

## Versions

- Node:  v12.16.1
- NPM:   6.13.4
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [x] 1.5.0
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
@momtboy test it in the new version 2.0.0 and let me know if the issue perssists

**Comment by diegoazh** [comment]
Working well on v2.0.3, please read the new way to import the plugin. Let me know if you have issues. Thanks and regards.
