### ISSUE TITLE
Autocomplete is undefined

### ISSUE THREAD

**Issue by josegus** [diegoazh/gmap-vue#13]
I get this error when using autocomplete and places, the most stranger thing is that i've another component with autocomplete working good.

![image](https://user-images.githubusercontent.com/13947849/83343415-f4f35200-a2c7-11ea-8984-02794fdf3701.png)
![image](https://user-images.githubusercontent.com/13947849/83343429-1f450f80-a2c8-11ea-9b74-9511eba6450f.png)
![image](https://user-images.githubusercontent.com/13947849/83343442-3f74ce80-a2c8-11ea-8011-a454afa96b89.png)

**Comment by diegoazh** [comment]
Hello @josegus, sorry for my delay, can you provide a minimal repository to reproduce this issue?

**Comment by diegoazh** [comment]
@josegus try the new version 2.0.0, I will close this issue but feel free to reopen it if you need.
