### ISSUE TITLE
Feature: Polyline add support of icons prop

### ISSUE THREAD

**Issue by ygascard** [diegoazh/gmap-vue#132]
**Is your feature request related to a problem? Please describe.**
Hi!

As described here:
https://developers.google.com/maps/documentation/javascript/symbols#add_to_polyline

Polyline has an icons property to put symbols on the line. Unfortunately the Polyline component doesn't implement it.

**Describe the solution you'd like**
I think it's just a matter of adding the prop to the Polyline.js component I guess...

**Describe alternatives you've considered**
Well except writing my own component I don't see any.

**Additional context**

**Comment by ygascard** [comment]
I'm not familiar with the code but I almost made it work.

I added

  icons: {
    type: Array,
    twoWay: true,
  },

But I get 
Error: setIcons is not a method of (the Maps object corresponding to) gmap-polyline
Removing twoWay doesn't change.

I'd be glad to make my first pull request on this with a little help.

**Comment by clixmat** [comment]
I need also this functionality please @diegoazh

**Comment by diegoazh** [comment]
In all components you have an `options` prop there you can define all properties of the Google Maps component that we don't define as Vue props. Currently, I added props to all shapes but in the [circle API](https://diegoazh.github.io/gmap-vue/code/components/circle-shape.html#props) documentation, you can see an example about how to use it, on the other hand, in the documentation of the [circle source](https://diegoazh.github.io/gmap-vue/guide/circle.html#source-code) code, you can see how the options prop is spread inside of the `initialOptions` constant.
Let me know if that option works for you. Regards.
