### ISSUE TITLE
Need help on: Marker rotation

### ISSUE THREAD

**Issue by aphavichitr** [diegoazh/gmap-vue#135]
# What you try to do

Trying to rotate a marker by using the bearing. The native google maps marker API has a rotation option.

# What is the problem

Didn't see if this library supported marker rotation in the documentation and examples. Does this library support this?

# What kind of things have you already treated

Haven't tried this library yet

# Steps to reproduce

N/A

## Os

- [X] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [ ] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
@aphavichitr try the new version 2.0.0 and let me know if the issue perssists.

**Comment by diegoazh** [comment]
@aphavichitr can you check the options on the new v2.0.3? let me know If that option is not inclluded.

**Comment by aphavichitr** [comment]
> @aphavichitr can you check the options on the new v2.0.3? let me know If that option is not inclluded.

Sure let me test and get back to you. I've been using a custom calculation to rotate it, so I will need to change the implementation.

**Comment by Anjgpt** [comment]
@diegoazh Do we have the option to rotate the PNG marker?
As I'm not able to do this with the below approaches.

"gmap-vue": "^3.5.2",

<gmap-marker
        v-for="m, index in markers"
        :position="m.position"
        :icon="{
          url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/info-i_maps.png',
          rotation: 90,
        }"
        :key="index"
      />

Or 

Using style transform also not working.
<gmap-marker
        v-for="m, index in markers"
        :position="m.position"
        :icon="{
          url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/info-i_maps.png',
        }"
        :style="{ transform: 'rotate(90deg)' }"
        :key="index"
      />


If I'm doing this with SVG image it's working but there is slowness as I've lot's of markers.
