### ISSUE TITLE
Feature: Add overlaycomplete, fillColor, strokeColorstrokeColor props for DrawingManager

### ISSUE THREAD

**Issue by akc4** [diegoazh/gmap-vue#138]
**Is your feature request related to a problem? Please describe.**
For the moment when you complete/deselect/select, let's say a polygon, it will automatically go back to the colors set in ```/components-implementation/drawing-manager.js/```  on ```clearSelection()``` and ```setSelection()```.
It overwrites the options you set in (ex.):
```
polylineOptions: {
        fillColor: "#ff0000",
        fillOpacity: 0.7,
        strokeWeight: 2,
        strokeColor: "#ff0000",
        draggable: false,
        editable: false,
        clickable: true,
      },
```

**Describe the solution you'd like**
If possible add props.

**Describe alternatives you've considered**
For the moment I am doing this:
```
mounted() {
    setTimeout(() => {
      this.$refs.drawmanager.$drawingManagerObject.addListener(
        "overlaycomplete",
        (event) => {
          this.myFunction();
        }
      );
    }, 1000);
  },
```

**Additional context**

**Comment by diegoazh** [comment]
@akc4 can you check the new v2.0.3 and let me know if those options are not present, in some cases we give an `options` prop to use for that options that are not commonly used but that will be possible that someone needs on some cases.
