### ISSUE TITLE
v-model on  marker

### ISSUE THREAD

**Issue by josegus** [diegoazh/gmap-vue#14]
Would be nice if we could use v-model with a GmapMarker (along with current :position prop), since everytime I move the marker I need to update manually the new location lat and lng values

**Comment by diegoazh** [comment]
@josegus that sounds good for me, if you have any idea about how to implement this you are welcome to send your PR.

**Comment by diegoazh** [comment]
@josegus now we have an `update:position` event on markers, at the moment is not possible to use `v-model` directive of Vue 2 in this prop but in Vue 3 it will be possible.
I hope that this will be useful, check the [documentation](https://diegoazh.github.io/gmap-vue/guide/marker.html) for more details.
Regards.
