### ISSUE TITLE
Feature: Add On Load, OnFullScreen events

### ISSUE THREAD

**Issue by siba2893** [diegoazh/gmap-vue#140]
I would like to get some events to trigger certain functionality on my app. As when the map is fully loaded and can be used. Or when it goes into fullscreen.

**Comment by diegoazh** [comment]
@siba2893 please follow our issue template

**Comment by diegoazh** [comment]
Sorry for the boit @siba2893 I will check the option for full-screen, for loading I think you can use the promise to run a lading and when the promise resolves you can disable the loading.
Check this part o the documentation [lazy loading](https://diegoazh.github.io/gmap-vue/#lazy-loading).

**Comment by diegoazh** [comment]
All events are available, you cant take the component reference and add listeners to every event, something like the following

```js
    this.$mapObject.addListener('zoom_changed', () => {
      this.$emit('zoom_changed', this.$mapObject.getZoom());
    });
```

You can check the events [here](https://developers.google.com/maps/documentation/javascript/events).
The better way to detect if the map is loaded is using the `tilesloaded` event. to detect if the map is in fullscreen maybe [this answer on StackOverflow](https://stackoverflow.com/a/40900819/5302733) can help, they are using the `bounds_changed` event.
If this answer is helpful feel free to close this issue.
Regards.
