### ISSUE TITLE
Need help on: How to use this plugin with vue3

### ISSUE THREAD

**Issue by Ahmed-Shaheen2** [diegoazh/gmap-vue#141]
# What you try to do

trying to use this plugin with a vue3 project

# What is the problem

cant initialize the plugin with the ordinary steps mentioned in documentation  

# What kind of things have you already treated

nothing except trying to customize the install function a little bit but no result

# Steps to reproduce

just use a vue 3 project and try to initialize the plugin with code
Vue.createApp(app).
use(GmapVue, {...options});

## Os

- [ ] Linux (linux mint 20)

## Versions

- Node: v14.15.4
- NPM: 6.14.10
- Yarn:

## Package manager

- [ ] NPM

## Plugin version

- [ ] 1.5.0

**Comment by diegoazh** [comment]
@Ahmed-Shaheen2 you can't use this plugin with vue3, currently, I am rewriting many parts of the plugin for vue2 and after that, I will try to move to vue3, on the other hand, I am needing help to work faster in the project you are welcome if you want

**Comment by rationalthinker1** [comment]
@diegoazh, I can help with the upgrade. Can you guide me on what I can do? What's the main issue with the upgrade? Any particular part that is time-consuming?

**Comment by diegoazh** [comment]
@rationalthinker1 I was working on a restructuration and refactor of the plugin that takes so much time. I will start planning the new version

**Comment by diegoazh** [comment]
I will start the upgrade soon, now Vue 3 is the new LTS and default version.
