### ISSUE TITLE
Need help on: How to use this plugin with vue3 ?

### ISSUE THREAD

**Issue by Ahmed-Shaheen2** [diegoazh/gmap-vue#142]
# What you try to do

trying to use this plugin with a vue3 project

# What is the problem

cant initialize the plugin with the ordinary steps mentioned in documentation  

# What kind of things have you already treated

nothing except trying to customize the install function a little bit but no result

# Steps to reproduce

just use a vue 3 project and try to initialize the plugin with code
Vue.createApp(app).
use(GmapVue, {...options});

## Os

- [x] Linux (linux mint 20)

## Versions

- Node: v14.15.4
- NPM: 6.14.10
- Yarn:

## Package manager

- [x] NPM

## Plugin version

- [x] 1.5.0

**Comment by diegoazh** [comment]
We will start migrating it to Vue 3, if you want to collaborate you are welcome.
