### ISSUE TITLE
Need help on: Autocomplete basic input design by class name

### ISSUE THREAD

**Issue by findridoy** [diegoazh/gmap-vue#146]
# What you try to do

I am trying to inject classes to autocomplete basic component

# What is the problem

There are no mention in the doc how can I do that. Or I can not.

# What kind of things have you already treated

I haven't tried anything

# Steps to reproduce

You can try to change design on component

## Os

- [ ]  Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [x ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: 12
- NPM: 6
- Yarn:

## Package manager

- [ x] NPM
- [ ] Yarn

## Plugin version

- [ x] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
can you please provide a snippet or minimum repository to visualize better what you need?
