### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by ljcremer** [diegoazh/gmap-vue#15]
Do you have any plans to convert this to Vue 3?

**Comment by diegoazh** [comment]
Hello @ljcremer, thanks for your question. The answer is a big YES! my first goal is to migrate this plugin to Vue 3 when it is in a stable state. If you would like to contribute to making it possible please let me know. Regards

**Comment by zeroedin** [comment]
I'm definitely going to be watching the project. I dunno how much I'll be able to contribute just from lack of general skill with Vue, but am interested in this project and will try to offer what I can.

**Comment by ljcremer** [comment]
@diegoazh Do you know if this has been started. We would like to collaborate on this. If nothing has been done yet we could potentially start looking into it.

**Comment by diegoazh** [comment]
@ljcremer no we did not start the migration yet, I would like to have help and collaborators, you are welcomed but first, we need to improve the actual version and planing the migration to not repeat the same errors when this plugin starts, we need a clear structure and definitions in order to get a better plugin and documentation in the future.

**Comment by andreavettore** [comment]
Hello,
any ETA for vue3 support?

**Comment by diegoazh** [comment]
Hi @andreavettore I'm currently working on that, my goal is first to land a version with typescript and use the options API and after that work on changes to use the composition API.
At the moment I'm having issues with types and changes on the google maps API but the work goes well but slow.
I hope to finish this weekend or the next, but before landing the Vue 3 version I would like to merge some fixes on the Vue 2 version and land the Vue 3 version with all those fixes on it.

**Comment by andreavettore** [comment]
@diegoazh sounds good. Thanks a lot!

**Comment by websitevirtuoso** [comment]
Any news? DO I need to wait or better implement native google maps API?

**Comment by diegoazh** [comment]
I'm working on this issue but it is taking so much time, I'm trying to remove all unnecessary, unuseful and unused code there, move to typescript, test it (UT) and try to build an e2e layer too. Working alone is difficult to make significant and fast progress.
My apologies @websitevirtuoso.

**Comment by ChaudharyHabib** [comment]
any updates on vue3?

**Comment by websitevirtuoso** [comment]
If somebody need vue3. You can use this repo
https://github.com/NathanAP/vue-google-maps-community-fork
