### ISSUE TITLE
Feature: Update gmap version handling description

### ISSUE THREAD

**Issue by CamilleDrapier** [diegoazh/gmap-vue#151]
**Is your feature request related to a problem? Please describe.**
Update gmap version handling description in `packages/gmap-vue/src/manager/initializer.js`, as it is falsely claiming that this is a parameter that will have effect. It is too late (and not related to this fork) for that, but the removal of the `version` option should have probably been documented in a major's version breaking change entry.

**Describe the solution you'd like**
The documentation of `packages/gmap-vue/src/manager/initializer.js` references a `version` option that is not handled anymore and that is ignored by Google maps API. The documentation should probably be updated to remove this part as well as other comments referencing it (`apiKey`). This could be updated to reference https://developers.google.com/maps/documentation/javascript/url-params

**Describe alternatives you've considered**
- restore some code that would use the `version` option and forward it to google API if `v`. is not provided 

**Additional context**
`version` handling was:

* implemented: https://github.com/xkjyeah/vue-google-maps/commit/107b1a31bf5dfd981481482b6827646b28d44242
* changed: https://github.com/xkjyeah/vue-google-maps/commit/f2a5a85b3e12533ba6d79b5dc56de884e7b262ea
* changed: https://github.com/xkjyeah/vue-google-maps/commit/056e5c047cce6670ec3479b3dfa1e0df94fd72af#diff-4765f4f1bcc70a9139235dcba80e47958c35dd98968356ea65af5971e995b432
* removed: https://github.com/xkjyeah/vue-google-maps/commit/f69e88e838f8304fb535ee03a2377d6c90fa1b61#diff-4765f4f1bcc70a9139235dcba80e47958c35dd98968356ea65af5971e995b432

The `v` option is referenced in this documentation from quite a long time: https://github.com/diegoazh/gmap-vue/commit/f80cb48c1d5b02a8d6c84a901f18227b411514e3

The google versioning documentation: https://developers.google.com/maps/documentation/javascript/versions

**Comment by CamilleDrapier** [comment]
Should be just about reviewing the PR I made.... :bow:  :pray:

**Comment by jpoehnelt** [comment]
I recommend using @googlemaps/js-api-loader for this. I can submit a pr in the next few days with this improvement.

**Comment by diegoazh** [comment]
@CamilleDrapier what was the PR? sorry I was focused on refactoring the plugin and trying to make it more readable and intuitive and I miss you PR.

**Comment by diegoazh** [comment]
Merged! Thank you so much!
