### ISSUE TITLE
Bug: ReferenceError: google is not defined inside google scripts

### ISSUE THREAD

**Issue by bhattjaldhi** [diegoazh/gmap-vue#154]
**Describe the bug**
I am using `prerender-spa-plugin` npm package to generate prerendered pages for better SEO. But after the build is generated and serve, it shows errors in the console `ReferenceError: google is not defined` in google scripts. However, the map is loaded properly but those errors are always present in the console.

Note: I do not face this error while in development mode

**Screenshots**
![image](https://user-images.githubusercontent.com/28974267/112723708-f2887580-8f35-11eb-967d-123de55462d8.png)

**Comment by diegoazh** [comment]
Please follow out issue template, if the issue persist please feel free to open a new issue.
