### ISSUE TITLE
Wrong install command?

### ISSUE THREAD

**Issue by yze77** [diegoazh/gmap-vue#16]
Shouldn't
`npm install vue2-google-maps`
instead be
`npm install gmap-vue`

and
`import * as VueGoogleMaps from 'vue2-google-maps'`
instead be
`import * as VueGoogleMaps from 'gmap-vue'`

The reason for this, is that I could not get custom text field via scoped slot to work with the gmap-autocomplete component.

I looked in _node_modules/vue2-google-maps/dist/components/autocomplete.vue_ in my project folder, and saw:
```
<template>
  <input
    ref="input"
    v-bind="$attrs"
    v-on="$listeners"
    />
</template>
```

I.e, No support for slots

Then I looked in you github repository in packages/gmap-vue/src/components/autocomplete.vue and saw:
```
<template>
  <span v-if="$scopedSlots['input']">
    <slot name="input" v-bind:attrs="$attrs" v-bind:listeners="$listeners" :ref="input"></slot>
  </span>
  <input v-else-if="!$scopedSlots['input']" ref="input" v-bind="$attrs" v-on="$listeners" />
</template>
```

I.e, support for slots.

So I unistalled vue2-google-maps via:
`npm uninstall vue2-google-maps`

and then ran
`npm install gmap-vue`

and changed
`import * as VueGoogleMaps from 'vue2-google-maps'`
to
`import * as VueGoogleMaps from 'gmap-vue'`
in my main.js and then the "slots" started to work.

**Comment by yze77** [comment]
I found the link to your documentation now. Sorry
https://diegoazh.github.io/gmap-vue/

**Comment by diegoazh** [comment]
@yze77 check the new documentation if you find any error please feel free to make a PR or open an issue again, Thank you.
