### ISSUE TITLE
Bug: map option 'streetViewControl=false' offsets 'vue-map' child when opening <InfoWindow>

### ISSUE THREAD

**Issue by jonHaultrax** [diegoazh/gmap-vue#169]
**Describe the bug**
When the map component is configured with {streetViewControl: false} and an <InfoWindow> is set to opened, the child of the "vue-map" element becomes incorrectly offset

**To Reproduce**
1. Set map component 'options' to {streetViewControl: false}
2. Set map 'zoom' level to 15
3. Set map 'center' to {lat: 10, lng: 10}
4. Set <InfoWindow> 'position' to {lat: 10, lng: 11}
5. set <infoWindow> 'opened' to true
6. Map appears white or has partially offset map tiles 

Reproduction html file found here: https://gist.github.com/jonHaultrax/3d2e789132b2ca561b4483974b725195

**Expected behavior**
Map should remain visible and a camera pan should be triggered (behaviour when streetViewControl=true)

**Current behavior**
The child of "vue-map" is no longer visible/child is offset from main map container

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] any
 - Browser [e.g. chrome, safari] any
 - Version [e.g. 22] any

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] any
 - OS: [e.g. iOS8.1] any
 - Browser [e.g. stock browser, safari] any
 - Version [e.g. 22] any

**Additional context**
N/A

## Versions

- Node: N/A
- NPM: N/A
- Yarn: N/A

## Package manager

- [ ] NPM
- [ ] Yarn

## Plugin version

- [x] 1.4.x
- [x] 1.2.x
- [x] 1.0.x

**Comment by jonHaultrax** [comment]
As far as I can tell there is no missing section so I don't understand why it was bot closed. I may just be blind though.

**Comment by diegoazh** [comment]
Hi, @jonHaultrax please try the new version 2.0.0 and check the new documentation. let me know if the issue persists.

**Comment by diegoazh** [comment]
You need to update the center of the map too, I only added this line `this.center.lng += 1;` to your `onTriggerIssue` method and it works as expected.

```js
// ...
  onTriggerIssue() {
    this.isOpen = true;
    this.infoWindowPos.lng += 1;
    this.center.lng += 1;
  },
// ...
```
