### ISSUE TITLE
Proper way to use gmapApi

### ISSUE THREAD

**Issue by r94ever** [diegoazh/gmap-vue#17]
Hi,

Please make me clearly about the way to using gmapApi. I copied your sample code but it didn't work:

```javascript
import { gmapApi } from 'gmap-vue'

export default {
  computed: {
    google: gmapApi
  },

  mounted () {
    console.log(this.google)
  },
}
```

The log displayed on the console is `NULL`

What wrong I made?
Thanks

**Comment by rodsouto** [comment]
It doesn't work in `mounted()` because the map is not initialized yet, but `this.google` will be available once  the map is ready

**Comment by r94ever** [comment]
> It doesn't work in `mounted()` because the map is not initialized yet, but `this.google` will be available once the map is ready

How to check when map is ready? Has any event be fired? Sorry since this is the first time I work with google map.

**Comment by rodsouto** [comment]
There is an example in the readme

```javascript
mounted () {
    // At this point, the child GmapMap has been mounted, but
    // its map has not been initialized.
    // Therefore we need to write mapRef.$mapPromise.then(() => ...)

    this.$refs.mapRef.$mapPromise.then((map) => {
      map.panTo({lat: 1.38, lng: 103.80})
    })
  }
```

**Comment by r94ever** [comment]
Worked like a charm! Thanks
