### ISSUE TITLE
How can draw in map

### ISSUE THREAD

**Issue by mstfkhazaal** [diegoazh/gmap-vue#170]
I have a map and I have to draw it, to demarcate the borders of each piece of land separately.
How do I do this with this library

Like this image
![1_vr4Cqg_FRtG50D9nZch14Q](https://user-images.githubusercontent.com/47450090/121904607-02904400-cd32-11eb-8685-cfacff3cd7c4.png)

**Comment by diegoazh** [comment]
duplicate
