### ISSUE TITLE
Need help on: How can draw in map

### ISSUE THREAD

**Issue by mstfkhazaal** [diegoazh/gmap-vue#171]
# What you try to do

I try Drawing Manager
# What is the problem

I have a map and I have to draw it, to demarcate the borders of each piece of land separately.
How do I do this with this library

# What kind of things have you already treated
I tried drawing through DrawingManager

# Steps to reproduce

Like this image
![1_vr4Cqg_FRtG50D9nZch14Q](https://user-images.githubusercontent.com/47450090/121904960-513dde00-cd32-11eb-91ed-599b40d76cf2.png)
## Os

- [x] Mac Os X
- [x] Linux (write here the name and version of your distribution)
- [x] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: 14.17.0
- NPM: 6.14.13
- Yarn: 1.22.5

## Package manager

- [x] NPM
- [x] Yarn

## Plugin version

- [x] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
I think you need to use polygons, check the new documentation and try to implement it.

**Comment by diegoazh** [comment]
Can you test the new v2.0.3 @mstfkhazaal?
