### ISSUE TITLE
Need help on: 

### ISSUE THREAD

**Issue by lombo75** [diegoazh/gmap-vue#173]
# What you try to do
Can someone please help me with an example or tell me whether it is possible to have multiple autocomplete and maps  in v-for on a single page where the map updates for the address entered per autocomplete. I also have this in a bootstrap-vue tabs pane and dont know if thats affecting anything

![image](https://user-images.githubusercontent.com/5086725/122950855-26055f80-d3c0-11eb-9211-9909f49b267f.png)

Explain to us what you are trying to do or what is your goal.

I want to be able to enter multiple addresses and show the address on the map for each address

# What is the problem
map changes to same address when i enter a new address in each autocomplete input

Explain to us what is the problem or what is the part of the documentation that is not clear.
Documentation doesnt show how to do this, or aybe I dont understand something thats needed

**Comment by diegoazh** [comment]
I will try to take a look at this, but in the first place are issues while I close issues try to test the new version 2.0.0 and check the new documentation, on the other hand, is possible that we switch to GitHub discussions for help.

**Comment by diegoazh** [comment]
Hi, can you share your implementation with us or a minimum repository? to check this behaviour.
