### ISSUE TITLE
Feature: Add the title prop to GmapCluster

### ISSUE THREAD

**Issue by mcadecio** [diegoazh/gmap-vue#177]
**Is your feature request related to a problem? Please describe.**
At the moment, when a user hovers on a cluster, a tootle tip does not show. The title is present in the element but there is no way to set a value through the component. (a prop has not been specified in the `cluster.js` file)

**Describe the solution you'd like**
I would like to be able to set the title for a gmap cluster through a prop value.

The solution is quite simple:

Add the following to the props variable in `cluster.js`:

```
 title: {
    type: String,
    twoWay: false      // we don't need a listener on the title
  }
```

**Describe alternatives you've considered**
Not need, simple request.

**Additional context**
No additional context.

**Comment by diegoazh** [comment]
Hi, @mcadecio  can you test the new version 2.0.0 and let me know if is possible if not I will land this change on the next version.

**Comment by diegoazh** [comment]
In the new library that we use for clusters, I can't see any option to set a title on the cluster icon, I let you the link [here](https://googlemaps.github.io/js-markerclusterer/modules.html) if you find the way to set the title please let me know or, also, you can make a PR, contributions are welcomed; until having an answer for you I'll maintain this issue closed.
Thank you and regards.

Link to [Google Maps documentation](https://developers.google.com/maps/documentation/javascript/marker-clustering)
