### ISSUE TITLE
Feature: Any examples for nearby places?

### ISSUE THREAD

**Issue by adavie1** [diegoazh/gmap-vue#185]
Autocomplete works great. But I want to get nearby places. Which apparently uses the places library. I've checked the Google Maps API and can't get my head around it.

**Comment by diegoazh** [comment]
Hi @adavie1 now I think that I understood you, I will try to land improvements on some components, including autocomplete and some others.

**Comment by diegoazh** [comment]
Hi, @adavie1 I checked the Google Maps API documentation and the nearby places are only a request, that you can make, I think that could be made from your application and the plugin doesn't need to implement that, after the request is made you can pass into the map the coordinates to display markers on it.
If your idea was in another direction please let me know here, on the other hand, you can try to test the following [example](https://developers.google.com/maps/documentation/places/web-service/search-nearby#nearby-search-example) with `axios` or `fetch` API.
