### ISSUE TITLE
Feature: Component gmap-drawing-manager

### ISSUE THREAD

**Issue by robertowiest** [diegoazh/gmap-vue#198]
Hi, I need to use the gmap-drawing-manager component and get the coordinates from the polygnom draw. Are there any examples of how I can do this?

**Comment by davydnorris** [comment]
Hey @robertowiest,

Have a look at the examples - the shapes prop is an array that will contain all the shapes you draw. If you draw a Polyline then it will contain a google.maps.Polyline object. If you check the Google Maps API reference for this object you'll see it has a path property, which is an array of lat/lng pairs

**Comment by diegoazh** [comment]
Hi, @robertowiest  as said @davydnorris take a look at the new documentation and its examples all components are working and you have documented the API of every component, on the other hand, this issue doesn't meet our issue template and its very possible that you solve it your problem with the examples if you need something extra, please open a new issue thanks.
