### ISSUE TITLE
Need help on: How do I attach an Object data to a single marker, and how do I show/hide a single marker?

### ISSUE THREAD

**Issue by tpkee** [diegoazh/gmap-vue#200]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## What you try to do

I'm trying to attach an Object data to the object marker, and hide it if it's 

## What is the problem

I don't know how, or if it's possible at all with this plugin, attach an Object data to the marker, and how to show/hide it based on a filter

## What kind of things have you already treated

Read the docs but they are laking.

## Steps to reproduce

There's not much you can toy with

## Os

- [X] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: 16.10.0
- NPM:
- Yarn: 1.22.11

## Package manager

- [ ] NPM
- [ X] Yarn

## Plugin version

- [ X] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
I will try to close the issues and after that, I will try to focus on the help, is possible too that in the short term we use GitHub discussions for help instead to use issues for that. Sorry for my delay.
