### ISSUE TITLE
Bug: Including eslint-plugin-vue 6 breaks with eslint 7

### ISSUE THREAD

**Issue by mryellow** [diegoazh/gmap-vue#203]
## Describe the bug

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gmap-vue@1.5.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^6.2.2" from the root project
```

## To reproduce

1. Install `gmap-vue`
2. Build Vue app
3. See error

## Expected behavior

Run without error.

## Current behavior

Errors.

## Screenshots

NA

## Desktop (please complete the following information)

 - OS: Debian 10
 

## Smartphone (please complete the following information)

NA

## Additional context

NA

## Versions

- Node v14.15.1
- NPM 7.6.0

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

What plugin?

**Comment by diegoazh** [comment]
yes, I'm trying to reorganize and restructure the entire plugin but it is taken a big effort and time. Can you check with the new version 2.0.0?

**Comment by mryellow** [comment]
Will do, might take me a little bit to get onto it.

**Comment by mryellow** [comment]
I still have this page open and still haven't got to it.

**Comment by diegoazh** [comment]
Sorry for that @mryellow I'll take a look as soon as possible.

**Comment by mryellow** [comment]
Sorry I haven't had a chance to check it. Have cycled back onto the involved project so getting closer, although it has been worked around in the meantime.
