### ISSUE TITLE
Need help on: Tinting a PNG marker - change marker color

### ISSUE THREAD

**Issue by dhcmega** [diegoazh/gmap-vue#204]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## What you try to do

I'm trying to use a PNG as marker and tint its color

## What is the problem

With this format, color and rotation are used
```js
                  path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
                  rotation: marker.heading,
                  strokeColor: markerColor(guardTrackingData, index)
```

but with PNG they are ignored
```js
                  url: getArrow(marker.heading),
                  scaledSize: { width: 25, height: 25 },
                  strokeColor: markerColor(guardTrackingData, index),
                  color: markerColor(guardTrackingData, index),
```

## What kind of things have you already treated

icon is ignoring the color (and rotation, but is not that important)

## Steps to reproduce

Simple try a PNG as marker

## Os

- [X] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [ ] NPM
- [x] Yarn

## Plugin version

- [x] 1.5.x
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
Hi @dhcmega can you try the new version 2.0.0? check the new example page to see an example with custom markers, remember that you need to use a valid google maps key.

**Comment by dhcmega** [comment]
Hi @diegoazh absolutely. I will test it this week. Thank you.

**Comment by dhcmega** [comment]
Hi @diegoazh something didn't work. I was using 1.5.0 and now I have installed 2.0.0.

`yarn add gmap-vue`

```
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ gmap-vue@2.0.0
info All dependencies
└─ gmap-vue@2.0.0
✨  Done in 2.41s.
```

`yarn dev` (as usual)

This dependency was not found:

* gmap-vue in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dashboard/security-guards/checkins/Checkins.vue?vue&type=script&lang=js& and 8 others

To install it, you can run: npm install --save gmap-vue

I have also tried deleting node_modules and reinstalling all
main.js has this line:

`import * as GmapVue from 'gmap-vue'`

And the IDE is telling me that the package is not installed.

Any suggestions?
Thanks!

**Comment by diegoazh** [comment]
Yes @dhcmega something was wrong on the CI/CD follow it on the issue #226 I'm working in the fix, and I will deploy a new version and deprecate the version 2.0.0, wait for it please.

**Comment by dhcmega** [comment]
Hi @diegoazh, I have checked the issue #226, I will wait until is finished to check it, thanks!

**Comment by dhcmega** [comment]
Hi @diegoazh, just in case, I'm still getting `[Vue warn]: Unknown custom element: <GmapMap> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`, even with 2.0.2.
Thanks

**Comment by diegoazh** [comment]
> Hi @diegoazh, just in case, I'm still getting `[Vue warn]: Unknown custom element: <GmapMap> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`, even with 2.0.2. Thanks
> 
> Edit:
> 
> main.js:
> 
> ```
> import * as GmapVue from 'gmap-vue'
> 
> Vue.use(GmapVue, {
>   load: {
>     key: 'hidden',
>     libraries: 'places,drawing,visualization', // This is required if you use the Autocomplete plugin
>   },
>   installComponents: true,
> })
> ```
> 
> my component:
> 
> ```
> import { gmapApi } from 'gmap-vue'
> 
> 
> 
> computed: {
>       google: gmapApi,
> },
> ```
> 
> and of course, it works on 1.5.0.
> 
> Thanks

Please change

```js
import * as GmapVue from 'gmap-vue'
```
for 
```js
import GmapVue from 'gmap-vue'
```

**Comment by dhcmega** [comment]
it worked. Thanks!
