### ISSUE TITLE
Bug: Autocomplete error("This page can't load Google Maps correctly.")

### ISSUE THREAD

**Issue by tpkee** [diegoazh/gmap-vue#205]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## Describe the bug

The autocomplete module doesn't work correctly, as it gives the following error "This page can't load Google Maps correctly". Just use it to see it not working. It doesn't work on the example page too
## To reproduce

1. Use the autocomplete tag, it won't work

## Expected behavior

A list of places

## Current behavior

It gives an error

## Screenshots

None

## Desktop (please complete the following information)

 - OS: macOS
 - Browser: Chromium, Firefox, Safari
 - Version: latest

## Smartphone (please complete the following information)

 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: NA

## Versions

- Node: 14.18.1
- NPM:
- Yarn: 1.22.11

## Package manager

- [ ] NPM
- [X] Yarn

## Plugin version

- [X] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
Please try with the latest version `v2.0.0` I refactored the entire structure of the plugin and as you can see in the new documentation page all components works expect two that are deprecated.

**Comment by diegoazh** [comment]
The autocomplete component is working well on v2.0.3
