### ISSUE TITLE
Is there support for drawing freehand?

### ISSUE THREAD

**Issue by Anjgpt** [diegoazh/gmap-vue#21]
Just wanted to check gmap-vue give support to draw freehand if yes then how?

Any help greatly appreciated.

**Comment by davydnorris** [comment]
have a look at the pull request I added - adds support for the drawing manager, which lets you draw freehand

**Comment by Anjgpt** [comment]
Thanks @davydnorris , i've checked the changes which looking amazing.
Any idea when this pull request can be merged?

**Comment by davydnorris** [comment]
Unfortunately that's not up to me - @diegoazh?

You can get the drawing manager going without the changes being merged - I've attached my test project so you can see how it works. I use Vuetify for my components, and I have two maps set up. Map.vue uses my own custom toolbar for editing, and Map2.vue uses the built in Drawing Manager bar and lets you randomly change its position
 
[map-test.zip](https://github.com/diegoazh/gmap-vue/files/4979139/map-test.zip)

**Comment by diegoazh** [comment]
Hello @davydnorris and @Anjgpt I am very busy the last months and I don't have time to take a look nothing and I feel bad for that, sorry guys.
This weekend I review all issues in the repo and merge PRs if they are good.
Please feel free to contribute or make any suggestions.

**Comment by diegoazh** [comment]
@Anjgpt I'm not sure if your question is answered or if the PR of @davydnorris solves your issue, please let me know.

**Comment by Anjgpt** [comment]
> @Anjgpt I'm not sure if your question is answered or if the PR of @davydnorris solves your issue, please let me know.

Hello @diegoazh first of all thank you so much for such an amazing plugin. Yes my question is answered by @davydnorris.

**Comment by Anjgpt** [comment]
Hi @davydnorris , how we can get the polygon path once we draw the polygon?

I'm getting below object in setSelection method..
```
overlay: _.ej
type: "polygon"
```

**Comment by davydnorris** [comment]
@Anjgpt - the shapes required prop will contain an array of all the shapes you drew. For Polygons they are actually arrays of point arrays.

console.log the shapes prop and you'll see the arrays. Also have a look in the components source code - if the shapes prop contains shapes I redraw them on the map and then they can be edited, so the code will give you an idea of how to use them

**Comment by Anjgpt** [comment]
Thanks @davydnorris for a quick reply. Let me have a look in the components source code.

**Comment by diegoazh** [comment]
The new version of `GmapVue` is ready on npm
