### ISSUE TITLE
Bug: Uncaught Error: Dynamic require of gmap-vue/dist/components/autocomplete-input.vue is not supported

### ISSUE THREAD

**Issue by judocode** [diegoazh/gmap-vue#231]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## Describe the bug

I am trying to move a project to Vite, and this package seems to be the only hangup right now. I am getting an "Uncaught Error: Dynamic require of gmap-vue/dist/components/autocomplete-input.vue is not supported" when attempting to start my app.

## To reproduce

1. Clone repository https://github.com/judocode/vite-demo-vue2-gmap
2. Run yarn && yarn dev
3. Open http://localhost:3000

## Expected behavior

I expect the app to start up without error.

## Current behavior

The app starts up with the described error in the console.

## Desktop (please complete the following information)

 - OS: macOS Big Sur 11.6
 - Browser chrome
 - Version 95.0.4638.69

## Smartphone (please complete the following information)

 - N/A

## Versions

- Node: 14.17.1
- NPM: 6.14.13
- Yarn: 1.22.17

## Package manager

- [ ] NPM
- [x] Yarn

## Plugin version

- [x] 2.0.1
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
@judocode I think is an issue related with Vite not with the plugin, the library target is `umd` and works as expected with `vue-cli-service` I try in the web to and it works, but it throws in the browser the error that you mention when you use Vite to serve the site. Try to report it to the Vite repository is possible that some extra configuration will be needed.

**Comment by judocode** [comment]
@diegoazh Thanks for your reply! I can look into seeing if there is a workaround for Vite, although I've been unsuccessful thus far. I believe if you update this package to support ESM, this should fix it as well. ES modules are considered more modern, as ESM can handle CommonJS, and all modern browsers (except IE 11, soon to be EOL'd) handle it natively (which is a major benefit to how Vite/esbuild can achieve such great speed). And if you read the Node docs https://nodejs.org/api/esm.html, you will find "ECMAScript modules are the official standard format to package JavaScript code for reuse".

Here is a resource in which you can build to both CommonJS and ESM:
https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

You can find in official Vue packages the support for both:
https://github.com/vuejs/vue-router/blob/dev/package.json#L7-L8
https://github.com/vuejs/vuex/blob/dev/package.json#L8-L9

I would be happy to help with this as well, although given that it appears `gmap-vue` is written in ESM, it should be a pretty seamless update.

**Comment by judocode** [comment]
Here is some pretty good documentation as well!

https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html

**Comment by judocode** [comment]
Also looking into this further, it appears it could be possible to use this package with `import GmapVue from "gmap-vue/dist/gmap-vue";` (which is the [UMD file from the webpack output](https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/webpack.config.js#L27-L35)), however, that requires [MarkClusterer to be specified as external](https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/webpack.config.js#L25) and throws an error without it.

I *think* I have found a wild workaround where I can import the above with:
```js
import GmapVue from "gmap-vue/dist/gmap-vue";
```

and then specify in the Vite config:
```js
export default defineConfig({
  resolve: {
    alias: {
      MarkerClusterer:
        "node_modules/@googlemaps/markerclusterer/dist/index.umd.js",
    },
  },
}
```

**Comment by diegoazh** [comment]
Excellent I think your workaround can be the temporary solution here and maybe we can close the issue, among that I liked so much the resources that you share, and I'm will take a look deeper into that options, maybe for the next, I would like to test rollup as our main bundler for the library but I need to test it firs, on the other hand, I wouldn't like to delay the migration to Vue 3 any longer.

What do you think @judocode, can we close the issue with this workaround?

**Comment by diegoazh** [comment]
@judocode finally I got it. Can you confirm if this new version works fine on a Vite project?. Regards.

**Comment by judocode** [comment]
Seems to be working great, awesome work @diegoazh 🎉 !
