### ISSUE TITLE
How to use Clusters?

### ISSUE THREAD

**Issue by butaminas** [diegoazh/gmap-vue#234]
I'm looking through the docs (v.2.0.2) and noticed that it is inconsistent in regard to Cluster icons.

First, I tried:
```
import { components } from 'gmap-vue';
Vue.component('gmap-cluster', components.Cluster)
```
(as described in the guide section of the docs)
This ended up in `Unknown custom element gmap-cluster` error.

Then tried:
```
import GmapCluster from 'gmap-vue/dist/components/cluster'
Vue.component('GmapCluster', GmapCluster)
```
(as described in the Officially supported components section of the docs)

The component `cluster` doesn't even exist but there is `cluster-icon` so I tried importing this one.
This would make the cluster icons to show up on the map but I end up getting several errors in the console:

`Error in updated hook: "TypeError: this.$clusterObject.repaint is not a function"`

So how should this work?

**Comment by vesper8** [comment]
Seriously.. as mentioned above the cluster is not even in the node_modules folder. Tried with both `src` and `dist`. The documention is wrong. Anyone figure out how to use clusters?

**Comment by vesper8** [comment]
Tried reverting to `1.5.0` but that gave me some installation issues. Finally what worked for me was reinstalling `vue2-google-maps` and using the cluster from that package like I did before, and it does work `GmapCluster: () => import('vue2-google-maps/dist/components/cluster'),`

This will have to be a workaround until @diegoazh realizes he inadvertently removed `cluster` from his `2.0` release

**Comment by diegoazh** [comment]
@vesper8 @butaminas, good catch, it is my fault after writing the documentation I change it because the Vue linter rule enforces the name of the component with almost two words to avoid collision with the main library or other packages and I change to `cluster-icon` maybe that cause some issues that I didn't detect, I will take a look on that tonight but is very weird how the example page works fine, very tricky.

**Comment by diegoazh** [comment]
Take a look at the [example component](https://github.com/diegoazh/gmap-vue/blob/80362637df48da22f8b11013953d19439d2e688b/packages/documentation/docs/.vuepress/components/eg-basic-marker-cluster.vue#L46) in the documentation I'm importing it in that way and it works as expected, remember that you need to have installed the [`"@googlemaps/markerclusterer": "^1.0.13"`](https://github.com/diegoazh/gmap-vue/blob/80362637df48da22f8b11013953d19439d2e688b/packages/gmap-vue/package.json#L33) I recently noted that I forget that part in the documentation, my fault again.

**Comment by vesper8** [comment]
This also doesn't work for me. And your example is really confusing because it doesn't show how you load all the dependencies. Like where is your package.json that includes `@googlemaps/markerclusterer` ? 

Looking forward to a future release because clusters do not work at all with your latest release

**Comment by diegoazh** [comment]
@vesper8 @butaminas now the cluster should work as it's described in the documentation, please let me know if you found another error. Regards and thank you.

**Comment by razukc** [comment]
> @vesper8 @butaminas now the cluster should work as it's described in the documentation, please let me know if you found another error. Regards and thank you.

No. It still is not working. There is some error about _repaint_ not being a function at _updated_ hook in _cluster-icon.vue_ file. 
![image](https://user-images.githubusercontent.com/4814921/153572017-afbb1147-5add-4daf-9b34-de50639aa2da.png)

**Comment by diegoazh** [comment]
@razukc we can continue with the discussion on issue #118, I'll lock this issue to avoid duplications. Thanks.
