### ISSUE TITLE
Need help on: How to hide the drawing-control and set drawingMode by myself

### ISSUE THREAD

**Issue by ShenWinnie** [diegoazh/gmap-vue#236]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## What you try to do
Hide the drawing-control and set drawingMode by myself

## What is the problem
No props can set to do this.

## Steps to reproduce

```
<gmap-drawing-manager
  v-if="mapMode==='ready'"
  :drawing-control="false"
  position="TOP_CENTER"
  :rectangle-options="rectangleOptions"
  :circle-options="circleOptions"
  :polyline-options="polylineOptions"
  :shapes="[]"
/>
```

## Os

- [x] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by davydnorris** [comment]
See the example in the documentation that shows how to use the slot to supply your own toolbar and set the drawing mode
