### ISSUE TITLE
Bug: clusters do not work, documention is wrong

### ISSUE THREAD

**Issue by vesper8** [diegoazh/gmap-vue#238]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## To reproduce

Install 2.0.2 library.

Try to pull in clusters, either via `'gmap-vue/src/components/cluster'` or `'gmap-vue/dist/components/cluster'`

Receive error `Can't resolve 'gmap-vue/src/components/cluster`

Notice that inside `node_modules/gmap-vue/dist/components` there is no `cluster` but there is a `cluster-icon`

There is also no `src` folder

## Expected behavior

Clusters should work

## Current behavior

Clusters do not work, documentation is wrong.

## Screenshots

n/a

## Desktop (please complete the following information)

 - OS: mac
 - Browser chrome

## Package manager

- [ ] NPM
- [ x] Yarn

## Plugin version

- [x ] 2.0.x

**Comment by diegoazh** [comment]
@vesper8, continue the discussion on issue #234 for this time. I will take a look at the bot again, sorry.

**Comment by diegoazh** [comment]
Fixed in version 2.0.3
