### ISSUE TITLE
Feature: dynamically loading a google maps API key / config, without ENV variables

### ISSUE THREAD

**Issue by stitch** [diegoazh/gmap-vue#239]
## Is your feature request related to a problem? Please describe.

Yes: I'm trying to load the API key dynamically, as this is not known op app instantiation. The solution that works with an environment variable is not desirable as that complicates app deployment. We get the key via a JSON call.

## Describe the solution you'd like
Any way of loading in the API key / config dynamically, which does not require restarting the app. As mentioned in the examples below.

## Describe alternatives you've considered

Based on some searches and documentation, i came up with the known solutions that do not work in this fork.

### Method one: using the vue-google-maps docs:
`import {GmapVue, load} from 'gmap-vue'` as suggested from https://github.com/GuillaumeLeclerc/vue-google-maps#installation

In this case 'load' is not defined. So this wont work.

### Method two: attempting to call loadGmapApi
`GmapVue.loadGmapApi` as suggested in https://github.com/xkjyeah/vue-google-maps/issues/135

This does not work. While loadGmapApi is mentioned in the library, it cannot be used.

## Additional context

-

**Comment by diegoazh** [comment]
I liked your suggestion so much, I will take a look at these possible solutions.
