### ISSUE TITLE
Need help on: customize cluster icon

### ISSUE THREAD

**Issue by VirginieBouvarel** [diegoazh/gmap-vue#242]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## What you try to do
I would like to customize the cluster icon with a custom url src or with css class.

## What is the problem
only the default cluster-icon works properly.

## What kind of things have you already treated
the image-path works only with the google map default url, but not with local path,
the styles array seems doesn't work,
the clusterClass seems doesn't work.

## Steps to reproduce
Create a map, with markers and clustering and try to change the cluster icon style

## Os

- [ ] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [x ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v14.18.0
- NPM: 6.14.16
- Yarn:

## Package manager

- [x ] NPM
- [ ] Yarn

## Plugin version

- [x ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
@VirginieBouvarel, hi I will take a look at it as soon as I can.

**Comment by diegoazh** [comment]
@VirginieBouvarel have you checked the icon property that we have had since v2.0.0?

**Comment by VirginieBouvarel** [comment]
@diegoazh Thanks for your help! I finally got it how to use the styles object correctly, and I have could set my customs clusters. I think the url was wrong.

**Comment by diegoazh** [comment]
Nice, you're welcome.

**Comment by dhcmega** [comment]
hi @VirginieBouvarel 
can you share your code as an example? thanks

**Comment by Anjgpt** [comment]
Hi @diegoazh, I'm using gmap-vue ^3.5.2 and not able to pass the style prop and I can see style prop is not present in doc [here](https://diegoazh.github.io/gmap-vue/guide/cluster.html#source-code). in 1.x.x version it was present.
```
<gmap-cluster
    :styles="markerClusterStyles"
    @click="setSidePanel('cluster', $event)"
  >
```

**Comment by diegoazh** [comment]
Please read the following [comment](https://github.com/diegoazh/gmap-vue/issues/255#issuecomment-1076272469), I think that will solve your problem.
