### ISSUE TITLE
this.$clusterObject.repaint() is not a function

### ISSUE THREAD

**Issue by razukc** [diegoazh/gmap-vue#247]
@razukc we can continue with the discussion on issue #118, I'll lock this issue to avoid duplications. Thanks.

_Originally posted by @diegoazh in https://github.com/diegoazh/gmap-vue/issues/234#issuecomment-1036457506_

This is a different issue than #118. So, I had to create a new one here.

Try this here: https://stackblitz.com/edit/nuxt-starter-mjnhuy?ctl=1&embed=1&file=pages/index.vue

If you try editing the file (with any change that will trigger HMR), the above said error is also triggered.

**Comment by diegoazh** [comment]
@razukc when you open an issue please select some of the templates that we have, on the other hand, is this issue still happening on the last version (v3.0.0)?

**Comment by diegoazh** [comment]
With the Stackblitz that you share I can't see any error, nothing is thrown.

**Comment by dom-velloso** [comment]
Hi @diegoazh, I updated to v3.0.0 and gmap started throwing this same error.
`[Vue warn]: Error in updated hook: "TypeError: this.$clusterObject.repaint is not a function"

found in

---> <ClusterIcon> at node_modules/gmap-vue/dist/components/cluster-icon.vue
       <MapLayer> at node_modules/gmap-vue/dist/components/map-layer.vue`

<img width="518" alt="Screen Shot 2022-02-16 at 14 38 05" src="https://user-images.githubusercontent.com/59833288/154323459-547865d2-31e1-4f3b-8f71-5952f62703bc.png">

**Comment by razukc** [comment]
> With the Stackblitz that you share I can't see any error, nothing is thrown.

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-mjnhuy?file=pages%2Findex.vue
)
I added `setTimeout` of `1000 ms` to update value of `center` after the page is `mounted` and the error is triggered. Actually, you can try to change value of any property there. You can even try changing value for `GmapCluster`. The error is still thrown.

**Comment by diegoazh** [comment]
@razukc and @dom-velloso the bug was fixed. Thank you for reporting it. Regards.

**Comment by dom-velloso** [comment]
Cool, thanks @diegoazh

**Comment by razukc** [comment]
> @razukc and @dom-velloso the bug was fixed. Thank you for reporting it. Regards.

That's great! By the way, will you add `props` back to `cluster-icon`?

**Comment by diegoazh** [comment]
No, I'll not. Why? Do you need anything?

**Comment by razukc** [comment]
> No, I'll not. Why? Do you need anything?

Yes. I need `styles` & `clusterClass` in `<GmapCluster>`. There were `props` for them before.
Example: 
```
<GmapCluster
	:styles="[
          {
	      width: 30,
	      height: 30,
	      className: 'clustericon-1',
          },
	]"
	:clusterClass="'cluster-icon'"
>
```

**Comment by joe94113** [comment]
@diegoazh Awsome thanks.

**Comment by Anjgpt** [comment]
Hi @diegoazh @razukc , I'm using gmap-vue ^3.5.2 and not able to pass the style prop and I can see style prop is not present in doc [here](https://diegoazh.github.io/gmap-vue/guide/cluster.html#source-code). in 1.x.x version it was present.

<gmap-cluster
    :styles="markerClusterStyles"
    @click="setSidePanel('cluster', $event)"
  >

**Comment by razukc** [comment]
> Hi @diegoazh @razukc , I'm using gmap-vue ^3.5.2 and not able to pass the style prop and I can see style prop is not present in doc [here](https://diegoazh.github.io/gmap-vue/guide/cluster.html#source-code). in 1.x.x version it was present. Is there any other way to pass style prop?
> 
> <gmap-cluster :styles="markerClusterStyles" @click="setSidePanel('cluster', $event)"
> 
> >
@Anjgpt 
Lot has changed in a new version. Did not find a way to use a CSS class, so I ended up using:
`
<GmapCluster :options="clusterOptions">
    
</GmapCluster>
`
`clusterOptions` is a `computed` variable
`
clusterOptions() {
	return {
		renderer: {
			render: ({ count, position }) =>
				new google.maps.Marker({
				    label: { text: String(count), color: "white", fontSize: "16px" },
					icon: {
						path: google.maps.SymbolPath.CIRCLE,
						fillColor: "#d3010f",
						fillOpacity: 1,
						strokeWeight: 0,
						scale: 20,
					},
					position,
					zIndex: Number(google.maps.Marker.MAX_ZINDEX) + count,
			}),
		},
	};
},
`
