### ISSUE TITLE
Bug: rotateControl: true not activating the controls

### ISSUE THREAD

**Issue by dhcmega** [diegoazh/gmap-vue#251]
> Please complete all the sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't follow our issue template (you can remove this comment)

## Describe the bug

The option rotateControl is ignored, other option do work, like zoomControl

## To reproduce

Create a map with these options:
      mapOptions: {
        zoomControl: true,
        mapTypeControl: true,
        scaleControl: false,
        streetViewControl: true,
        rotateControl: true,
        fullscreenControl: true,
        disableDefaultUi: false,
      },

## Expected behavior

The control buttons for tilt and rotate should appear

## Current behavior

The control buttons are not showing up

## Desktop (please complete the following information)

 - OS: macOS
 - Browser Chrome
 - Version 98

## Versions

- Node:
- NPM:
- Yarn: 1.22.17

## Package manager

- [ ] NPM
- [x] Yarn

## Plugin version

- [x] 2.0.4
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by dhcmega** [comment]
Hi! Any updated on possible fix? Just asking
Thanks!

**Comment by diegoazh** [comment]
@dhcmega sorry for being late, I was working on migrating this plugin to Vue v3. I'm not longer maintain the plugin for Vue v2. Please try the new version [`@gmap-vue/v3`](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme)
