### ISSUE TITLE
v3.4.3 completely breaks GmapInfoWindow

### ISSUE THREAD

**Issue by vesper8** [diegoazh/gmap-vue#254]
Working perfectly on v3.4.2

On v3.4.3 the slot seems to be broken because my info window completely fails to appear.

v3.4.2:
<img width="287" alt="Screen Shot 2022-02-22 at 5 51 36 AM" src="https://user-images.githubusercontent.com/816028/155059980-f30aadd7-b23f-4876-9364-f779499049a7.png">

v3.4.3:
<img width="167" alt="Screen Shot 2022-02-22 at 5 50 03 AM" src="https://user-images.githubusercontent.com/816028/155060354-2018cd4e-3e2b-4614-9241-a49f8b33279c.png">

Love your package but it's a bit concerning how such regressions are slipping through the cracks...

**Comment by vesper8** [comment]
@diegoazh Sorry for not filling out your issue template, I hope you fix this bug anyway. Till then I'll be on `3.4.2`

**Comment by diegoazh** [comment]
@vesper8 can you share your implementation of the `info-window` component?

**Comment by diegoazh** [comment]
I tested v3.4.3 and it works as expected with the old form, using the options prop with content inside, and using the new prop content it works well too. I let you a print below:

![image](https://user-images.githubusercontent.com/10166935/156248203-80222720-b484-41cc-998f-8c551b3a7e00.png)

Please can you share your implementation or a minimum repository to reproduce your bug?

**Comment by diegoazh** [comment]
Thank you. It is weird because I only added new props. But, I'll check again and test your component.

**Comment by vesper8** [comment]
@diegoazh As I'm not using your new content prop, but instead just replacing the default slot with the content, perhaps this is what's causing the conflict? When the prop is not provided, it does not correctly fall back on the slot?

And what if both the slot and the prop was provided, which would take precedence?

**Comment by diegoazh** [comment]
The problem was the default content of the new `content` prop, at runtime, it overrides the content of the default slot.
I updated the documentation with a warning of using one of these two ways to pass data to the `InfoWindow` component and notice the user that the `content` prop has precedence over the default slot.
Can you test the new version and confirm if it is working as expected?
Regards.

**Comment by vesper8** [comment]
@diegoazh Can confirm everything works again in 3.4.4 : )

Thanks for the fix!

**Comment by vesper8** [comment]
@diegoazh On a side note, I'm using gmap-vue in a Vue 3 project right now, in combination with @vue/compat. Everything works fine but I get a few warnings in the CLI console. @vue/compat saves the day but I look forward to your new release that will be fully compatible with Vue 3 : ) I understand you're slowly getting that ready. Keep up the good work!
