### ISSUE TITLE
Feature: GmapCluster - Allow passing options to MarkererClusterer

### ISSUE THREAD

**Issue by alisspers** [diegoazh/gmap-vue#255]
## Is your feature request related to a problem? Please describe.

The GmapCluster component works great but doesn't allow customizing the end result. Specifically, we'd like to change the colors of the cluster icons to follow our site's color palette.

## Describe the solution you'd like

A way to pass in the [options allowed by MarkerClusterer](https://googlemaps.github.io/js-markerclusterer/interfaces/MarkerClustererOptions.html) to the GmapCluster component. We probably need the `renderer` option for our use case but all options would probably be good to support.

## Describe alternatives you've considered

None other than trying to pass in an `:options` prop to GmapCluster and setting `renderer` there, but with no luck.

## Additional context

Using an old version of gmap-vue (which used the markererplus package), we leveraged custom png:s for the cluster icons to achieve the following:

<img src="https://user-images.githubusercontent.com/208699/155111474-1b04a476-2a21-4a23-b573-b4e800eb4b32.png" alt="old version" style="max-width: 100%;" height="300">

With the new version we get this result (which is functionally OK but not as good looking when seen in the context of our website):

<img src="https://user-images.githubusercontent.com/208699/155111670-6cdbd81f-262e-44f1-afa4-ccf2c9a0e9af.png" alt="new version" style="max-width: 100%;" height="300">

**Comment by diegoazh** [comment]
Hi @alisspers did you try with the `options` prop? with that option you can set the properties of Google Map objects that we didn't map to Vue props. I mean for example with the `InfoWindow` component before v3.4.3 we didn't have a content prop but you could set it using the `options` prop like below

```vue
<template>
    <gmap-map :center="center" :zoom="15" style="width: 100%; height: 500px">
      <gmap-info-window
        :content="newOptionContent"
        :options="{
          content: 'this is my info window content',
        }"
        :position="infoWindowPos"
        :opened="infoWinOpen"
        @closeclick="infoWinOpen = false"
      ></gmap-info-window>

      <gmap-marker
        :key="i"
        v-for="(m, i) in markers"
        :position="m.position"
        :clickable="true"
        @click="() => toggleInfoWindow(m, i)"
      ></gmap-marker>
    </gmap-map>
<template>
```

Please can you try with the `option` prop first and let me know if that prop doesn't allow you to set the render property of MarkerClusterer.

**Comment by diegoazh** [comment]
Try to execute the function because the prop expects an object not a function reference, I mean

```vue
<GmapCluster :options="clusterOptions()">
<!-- ... -->
</GmapCluster>
```

**Comment by alisspers** [comment]
Thanks for getting back! Sorry, I forgot to mention that I had "clusterOptions" as a computed property in my example above.
I've also tried having it in a `data` property (plaing object) as well as hardcoding it into `<GmapCluster :options="{ renderer: ... }">`. No luck I'm afraid.

Did you take a look at those lines of code I linked? [L58-L63 in cluster-icon.vue](https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/components/cluster-icon.vue#L58-L63)
It seems to me that not the whole options object is passed, just map & markers?

**Comment by diegoazh** [comment]
@alisspers you're right, I'll fix it right now.

**Comment by diegoazh** [comment]
@alisspers can you test the new version and confirm if this component is working as expected?

**Comment by alisspers** [comment]
It didn't, but I've found another bug that causes it not to work. The prop specification states "algorithm" instead of "options" for the prop name: https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/components/cluster-icon.vue#L93-L100

I changed that locally and tried again, then it works!

**Comment by Anjgpt** [comment]
@alisspers does this work for you? I'm passing options and not able to apply the custom style.
```
<gmap-cluster
      :options="clusterOptions()"
    >
...
</gmap-cluster>
```

```
clusterOptions() {
      return {
        renderer: ({ count, position }) => new google.maps.Marker({
          label: { text: String(count), color: 'white', fontSize: '10px' },
          icon: VesselCluster,
          position,
          // adjust zIndex to be above other markers
          zIndex: Number(google.maps.Marker.MAX_ZINDEX) + count,
        }),
      };
    },

```

**Comment by alisspers** [comment]
@diegoazh sorry I forgot to update you here – it works great for me now. Really appreciate your work and your quick response to my issue.

@Anjgpt the "renderer" option must be an object. In your case, it should be a plain JS object with a method called "render". Then it works!
Like this:

```js
    clusterOptions() {
            return {
                renderer: {
                    render: ({ count, position }) => new google.maps.Marker({
                        label: { text: String(count), color: 'white', fontSize: '10px' },
                        icon: VesselCluster,
                        position,
                        // adjust zIndex to be above other markers
                        zIndex: Number(google.maps.Marker.MAX_ZINDEX) + count,
                    }),
                },
            };
        }
```

**Comment by Anjgpt** [comment]
Thanks, @alisspers for the quick response really appreciate it. It works now.

**Comment by jesscostello** [comment]
Should the changes above allow setting options on the cluster object or just allow adding rendering options? I have tried adding options to the cluster object but they don't seem to be picked up at all
`<gmap-cluster :options="{ minPoints: 2, maxZoom 10, }">`

**Comment by diegoazh** [comment]
In that case, we only added the renderer option to the defined props @jesscostello, on the other hand, the way you are using the `options` prop is correct; finally, I strongly recommend moving to the new version of this plugin for Vue 3, in that version we defined all cluster options as available props on the component.

**Comment by jesscostello** [comment]
@diegoazh thanks for confirming! In this case unfortunately the project I was working on had to stick on Vue 2 for the time being
