### ISSUE TITLE
Bug: mouse events don't trigger on <GmapInfoWindow> 

### ISSUE THREAD

**Issue by nate998877** [diegoazh/gmap-vue#258]
## Describe the bug

Mouse events attached to GmapInfoWindow don't trigger. The events tied to the actual tag appear to be moved with the flyaway, causing any custom functionality to be removed.

## To reproduce

initalize isOpened = true
```                   
 <GmapInfoWindow
                        :content="exampleContent"
                        @mouseout="isOpened = false"
                        @mouseover="isOpened = true"
                        :opened="isOpened"
                    >
```
This is an oversimplified example of how to view the problem. 

## Expected behavior

I expect the displayed window to have the mouseout/over events attached.

## Current behavior

I the displayed window does not have the mouseout/over events attached.

## Screenshots

N/A

## Desktop (please complete the following information)

 - OS: Debian 11
 - Browser tested on Chrome & Firefox

## Smartphone (please complete the following information)

N/A

## Additional context

Not Context to this problem, unrelated.
The content prop does not override the default slot as stated [here] (https://github.com/diegoazh/gmap-vue/blob/6c0d61cd02b977fb7abee72f5464428b517dfd40/packages/gmap-vue/src/components/info-window.vue#L87).

## Versions

- Node:14.X
- NPM:6.x
- Yarn:N/A

## Package manager

- [X] NPM
- [ ] Yarn

## Plugin version

Relevant dependenices

    "@googlemaps/markerclusterer": "^1.0.25",
    "gmap-vue": "^3.4.5",

**Comment by diegoazh** [comment]
can you provide a minimum repository?

**Comment by nate998877** [comment]
https://github.com/nate998877/gmap-example

the vue.use is in src/main.js

Notice, @mouseover, @mouseout, & @onclick do not trigger for the info window when their respective mouse events are triggered. The x does function properly.

**Comment by diegoazh** [comment]
Thanks, @nate998877 I'll take a look at it as soon as I can.
