### ISSUE TITLE
Bug: gmap-vue breaks in Nuxt unless defined as client side only

### ISSUE THREAD

**Issue by davydnorris** [diegoazh/gmap-vue#264]
## Describe the bug

A default install and configuration of gmap-vue into a Nuxt project as per the documentation will fail with the message "Document is not defined" when a page containing a map is displayed. This is due to the default Nuxt behavior of server side rendering, and the fact that the MapLayer component has a CSS style section in it.

## To reproduce

1. Create a new Nuxt project
2. Add gmap-vue library, and create a plugin file as per the documentation
3. Add the plugin and the transpile directive to nuxt.config.js as per the documentation
4. Add a gmap-map component to a page
5. Run the application. It will compile without error
6. Navigate to the page containing the map.

## Expected behavior

The map is displayed correctly

## Current behavior

The page will not display and will show a "Document is not defined" error

## Screenshots

N/A

## Desktop (please complete the following information)

 - OS: Windows
 - Browser any
 - Version 3.5.2

## Smartphone (please complete the following information)

 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

## Additional context

The issue is fixed by specifying that gmap-vue is a client side plugin. This is done via the following in nuxt.config.js:
```
  plugins: [
    { src: '@/plugins/gmap-vue', mode: 'client' }
  ],
```
The documentation on setting up in Nuxt should be updated to show this

## Versions

- Node: any
- NPM: any
- Yarn: any

## Package manager

- [X] NPM
- [X] Yarn

## Plugin version

- [X] 1.4.x
- [X] 1.2.x
- [X] 1.0.x

**Comment by diegoazh** [comment]
Hi, @davydnorris I update the following [stackblitz example](https://stackblitz.com/edit/github-52grpx) to the latest version of the plugin and it works, I can't see any error on the console.
Can you fork it and configure it to see the errors that you mention?

**Comment by davydnorris** [comment]
Your example doesn't actually draw a map, so this is why there's no error - the error occurs when the map is actually drawn

**Comment by diegoazh** [comment]
Ok, I will try on the next weekend.

**Comment by diegoazh** [comment]
Hi @davydnorris I will stop the maintenance of this plugin for Vue v2, the new version for Vue v3 is landed please try it [`@gmap-vue`](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme).

Thank you for your effort and work on this version of the plugin 💪🏼.
