### ISSUE TITLE
Bug: when the marker size is greater than 1000 map loading slowly and browsers getting hang

### ISSUE THREAD

**Issue by Anjgpt** [diegoazh/gmap-vue#267]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

## Describe the bug

I'm using "gmap-vue": "^3.5.2" and facing slow performance(Browser hang) when the marker size is greater than 1000. Is there any limit on plotting markers?
```
<gmap-cluster>
      <gmap-marker
        v-for="(m, index) in vesselsMarker"
        :position="m.position"
        :clickable="true"
        :draggable="true"
        :key="index"
      />
    </gmap-cluster>

```
## To reproduce

1. Create a project that shows a map with markers
2. Pass markers objects which have >1000 markers.
3. It tool some time to plot markers and browsers hangs.

## Expected behavior

If there is any limit on marker count it should be documented and I think 1k/2k markers should be plotted quickly.

## Current behavior

Map loading slowly and browsers getting hang.

## Screenshots

.
<img width="1278" alt="Screenshot 2022-04-13 at 5 42 40 PM" src="https://user-images.githubusercontent.com/25198268/163180750-8fab205f-3e54-40bb-9e0d-666e243afedd.png">

## Desktop (please complete the following information)

 - OS: MacOS. big sur
 - Browser chrome
 - Version [Version 100.0.4896.75 (Official Build) (x86_64)]

## Smartphone (please complete the following information)

 - Only Web

## Additional context

N/A.

## Versions

- Node: 16
- NPM:
- Yarn:

## Package manager

- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by davydnorris** [comment]
Have you tried doing the same just using plain Javascript and the Google Maps API directly? Would be good to have some comparisons to see if it's the overhead of Vue or not

**Comment by Anjgpt** [comment]
Hi @davydnorris , I've tried this with native Google Maps API and it's loaded within 1 sec.
https://codesandbox.io/s/vigorous-currying-z4t174?file=/index.ts

**Comment by davydnorris** [comment]
hmmm that's a shame - I'm playing around with the code for the various shapes at the moment so I'll see if anything stands out in terms of performance issues

**Comment by diegoazh** [comment]
We wait for your feedback @Anjgpt

**Comment by davydnorris** [comment]
@Anjgpt can I ask you to do us a favour?

Can you please try this out with:
 - vue-google-maps original library
 - gmap-vue with individual markers and not using the cluster
 - gmap-vue with the cluster as before, but no extra props
 - compare to the plain Javascript

I want to try and figure out where the performance issue is coming into play

**Comment by Anjgpt** [comment]
I've followed these steps mentioned in this article https://tighten.com/blog/improving-google-maps-performance-on-large-datasets/.

Looks like a looping marker component causing delay/slowness.

**Comment by davydnorris** [comment]
@Anjgpt was there one particular step that made the difference?

**Comment by Anjgpt** [comment]
This step.

> Instead of our markers being added directly to the map, we’ll initialize our clusterer object and add the markers to it inside of the plotMarkers method. Doing so allows us to reduce the template returned from the MyMap component down to the Google Map itself:

**Comment by davydnorris** [comment]
@Anjgpt oh that's weird - I thought you were already using the cluster because of your code example in the bug explanation?

Is your code any different to your initial report?

**Comment by Anjgpt** [comment]
@davydnorris I was using the <gmap-cluster> <gmap-marker> component earlier and now I've removed them and directly used google Maps API to plot marker and for cluster MarkerClusterer.

This speeds up the performance

**Comment by davydnorris** [comment]
OK so that sounds like a problem with either the MarkerCluster component or the Marker component.

If you are interested in helping try to locate the problem I'd love if you could set up the same data with the old vue-google-maps library. I am currently rewriting the Drawing Manager and shapes components, which is why I can't do it myself

**Comment by diegoazh** [comment]
Migrate to the [new version](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme) of the plugin for Vue v3
