### ISSUE TITLE
Need help on: Installation : You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by zecka** [diegoazh/gmap-vue#269]
## What you try to do

I'm currently use https://github.com/xkjyeah/vue-google-maps and try to move to gmap-vue. But I'm stuck on the installation.

I create a repository to reproduce the issue:
https://github.com/zecka/issue-on-gmap-vue

## What is the problem

After installation I only import plugin as follow in main.js

```js
import GmapVue from 'gmap-vue'
```
Then run "serve" task (`vue-cli-service serve`)

But got following error:

```
 error  in ./node_modules/gmap-vue/dist/components/drawing-manager.vue?vue&type=script&lang=js&

Module parse failed: Unexpected token (85:16)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       _this.$map.addListener('click', _this.clearSelection);
| 
>       if (_this?.finalShapes?.length) {
|         _this.drawAll();
|       }

 @ ./node_modules/gmap-vue/dist/components/drawing-manager.vue?vue&type=script&lang=js& 1:0-244 1:260-263 1:265-506 1:265-506
 @ ./node_modules/gmap-vue/dist/components/drawing-manager.vue
 @ ./node_modules/gmap-vue/dist/main.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.19.33.146:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

```

## What kind of things have you already treated

I try to update vue.config.js as describe [in documentation](https://diegoazh.github.io/gmap-vue/#vue-cli-v4-applications)

## Steps to reproduce

I create a repository with the issue:

https://github.com/zecka/issue-on-gmap-vue

## Os

- [ ] Mac Os X
- [x] Linux (Ubuntu 20.02)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v14.18.2
- NPM :6.14.15
- vue: ^2.6.10
- @vue/cli-service: ^4.5.13

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by zecka** [comment]
I added `@vue/cli-plugin-babel/preset` to babel.config.js preset and update `@vue/cli-plugin-babel` from `^3.12.1`  to   `~4.5.11` and now it's seems working well.

```javscript
module.exports = {
  presets: ["@vue/cli-plugin-babel/preset"],
}
```

**Comment by reisnobre** [comment]
I'm having this same issue. Is this solved?
