### ISSUE TITLE
Feature: remove core-js and let the bundler do the polyfilling

### ISSUE THREAD

**Issue by arjendejong12** [diegoazh/gmap-vue#270]
## Is your feature request related to a problem? Please describe.

The [explicit import](https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/main.js#L1...L2) of core-js is doubling the file size when importing the package with ES6.

## Describe the solution you'd like

I feel like you should let the bundler add polyfills instead of including all by default, as people usually handle polyfills themselves and ESM packages should not. You could do this with [useBuiltIns: 'usage'](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage). I think the following [babel.config.js](https://stackoverflow.com/questions/58712204/how-to-inline-rollup-babel-polyfills-for-ie11) might help you with that.

## Describe alternatives you've considered

No alternatives.

## Additional context

![image](https://user-images.githubusercontent.com/10572554/166477246-d4e0e798-c851-419c-b633-479bd6250f70.png)

**Comment by davydnorris** [comment]
I agree with this - was surprised when I saw core-js was an explicit add

**Comment by arjendejong12** [comment]
@diegoazh Need any help with this?

**Comment by davydnorris** [comment]
@arjendejong12 if you feel like doing it and testing and then setting up a pull request that would be great!
@diegoazh doesn't get on here very much so having it all ready would be great

I've refactored the Drawing Manager and now doing the Shapes components as well

**Comment by diegoazh** [comment]
@arjendejong12 I loved the analysis and as @davydnorris  said if you want and you can, please make a PR, I'm working on the migration of this plugin to the Vue 3 version with Typescript and I'm having a lot of issues with types.
I remember that I included that import when I update the Vue version and all imports and other parts of the code started throwing errors at build time, with core-js and regenerator-runtime the problem was solved but I never could finish understanding why these errors were happening.

**Comment by arjendejong12** [comment]
So I've cloned the repo and removed the following two lines:
https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/main.js#L1...L2
I tried to build the package and to my surprise no errors were thrown. I replaced the compiled dist map in one of my projects where I use GmapVue and it kept working, but the size of the package went down with almost two thirds.

![image](https://user-images.githubusercontent.com/10572554/173250666-b5c17efb-1f1f-40ed-8051-6c4b4b31ecf8.png)
![image](https://user-images.githubusercontent.com/10572554/173250689-ec158b62-23a0-4a2e-9410-f78ce47b857f.png)

So I was wondering if you could try removing the imports and see if it works for you? @diegoazh @davydnorris
