### ISSUE TITLE
Need help on: 

### ISSUE THREAD

**Issue by Schotsl** [diegoazh/gmap-vue#271]
## What you try to do

I want to style clusters with my own icon, but I can't find any examples. Is this even possible using this package?

## What is the problem

It isn't clear to me what prop I can use for styling the icons. I've seen people use "styles" in other issues but this prop isn't documented.

## What kind of things have you already treated

I've read the documentation but the only relevant prop I could find is `options` but this doesn't seem related to the styling and it isn't very well documented nor explained.

I've also tried `styles` and `icon` but neither one of these seems to work, although it might just be that I'm passing an invalid object for styling since I'm trying to guess the prop and their required values.

## Steps to reproduce

I don't think this field is needed

## Os

- [x] Mac Os X
- [ ] Linux
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v10.19.0
- NPM: v6.14.4
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by davydnorris** [comment]
you use icon, but need to do it for each marker inside the cluster. Here's an example from my own code, which uses custom responsive SVG based markers:

in the template inside a gmap-map section:
```
    <gmap-marker
      v-for="(m, index) in mapMarkers"
      :key="index"
      :position="m.location"
      :title="m.id"
      :icon="mapIcons[m.state.status]"
      :clickable="true"
      :draggable="false"
      :options="{optimized:false}"
      @click="updateSelection(m)"
    />
```

in the script:
```
import svgIcon from './svg.icons';

export default {
 data: () => ({
  mapIcons: {
    connected: { url: svgIcon('green', false), scaledSize: { width: 30, height: 30 }, anchor: { x: 15, y: 15 } },
    disconnected: { url: svgIcon('darkgreen', false), scaledSize: { width: 30, height: 30 }, anchor: { x: 15, y: 15 } },
    dormant: { url: svgIcon('darkred', false), scaledSize: { width: 30, height: 30 }, anchor: { x: 15, y: 15 } },
    unknown: { url: svgIcon('grey', false), scaledSize: { width: 30, height: 30 }, anchor: { x: 15, y: 15 } },
    error: { url: svgIcon('red', true), scaledSize: { width: 30, height: 30 }, anchor: { x: 15, y: 15 } },
    publish: { url: svgIcon('green', true), scaledSize: { width: 30, height: 30 }, anchor: { x: 15, y: 15 } }
  },
```

svg.icons:
```
const colourSets = {
  green: { high: '#00ff00', low: '#008000' },
  darkgreen: { high: '#006400', low: '#003200' },
  red: { high: '#ff0000', low: '#800000' },
  darkred: { high: '#640000', low: '#320000' },
  grey: { high: '#646464', low: '#323232' }
};

const svgIcon = (colour, radar) => {
  const svgMarker = `
    <svg width='60px' height='60px' version='1.1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'>
      <defs>
        <linearGradient id='Circle' spreadMethod='pad' x1='0' y1='0' x2='1' y2='1'>
          <stop offset='0' stop-color='${colourSets[colour].high}'/>
          <stop offset='1' stop-color='${colourSets[colour].low}'/>
        </linearGradient>
        <linearGradient id='Highlight' spreadMethod='pad' x1='0' y1='0' x2='1' y2='1'>
          <stop offset='0.1' stop-color='#ffffff'/>
          <stop offset='1' stop-color='${colourSets[colour].low}'/>
        </linearGradient>
      </defs>
      <circle class='front' fill='url(#Circle)' opacity='0.9' cx='15' cy='15' r='5.5'/>
      <ellipse transform='rotate(-45, 12.8, 12.8)' rx='3' ry='2' cx='12.8' cy='12.8' fill='url(#Highlight)' opacity='0.6'/>`;

  const svgRadar = radar
    ? `<circle id='back' fill='transparent' stroke='${colourSets[colour].high}' opacity='0.9' cx='15' cy='15' r='5.5' stroke-width='1'>
          <animate attributeName='r'
              from='5.5'
              to='15.5'
              dur='1.5s'
              begin='0s'
              repeatCount='2'
              fill='freeze'
              id='circ-anim'
          />
      <animate attributeType='CSS'
              attributeName='opacity'
              from='0.9'
              to='0'
              dur='1.5s'
              begin='0s'
              repeatCount='2'
              fill='freeze'
              id='circ-anim'
      />
    </circle>`
    : '';

  return 'data:image/svg+xml,' + encodeURIComponent((svgMarker + svgRadar + '</svg>').replace(/\s+/g, ' '));
};

export default svgIcon;
```

**Comment by Schotsl** [comment]
Thanks for your reply! Altough I don't think I fully understand.. This is my HTML / Vue

```
<cluster :zoom-on-click="true">
  <gmap-marker
    v-for="insight in insights"

    :key="insight.id"
    :icon="marker"
    :position="getLocation(insight)"
    :clickable="true"

    @click="setInsight(insight)"
  />
</cluster>
```

```
data() {
  return {
    marker: {
      url: '/wp-content/themes/roots/assets/img/marker.svg',
      size: {
        width: 25,
        height: 25,
      },
    },
  }
}
```

So I got markers set, but the cluster still shows the default cluster icon? Perhaps I am missing something :(

**Comment by davydnorris** [comment]
@Schotsl can you try the same thing without the cluster and see if the markers customise then? I want to eliminate any problem with your url first

The cluster component is actually just a wrapper round a third party component [markerclusterer](https://www.npmjs.com/package/@googlemaps/markerclusterer). Looking at the code in that, it may be you will have to supply a render function that customises the marker. There's examples on the component's page

**Comment by Schotsl** [comment]
The URL is fine since every marker has a custom icon. I think you're right about replacing the renderer with a custom one for setting cluster icons. I'll try it out today and get back to you! :)

**Comment by Schotsl** [comment]
Thank you so much for your help! I turned out that I did have to rewrite my own render class, it ended up looking something like this

```
export default class Renderer {
  render({ count, position }) {
    return new google.maps.Marker({
      icon: {
        url: '/wp-content/themes/roots/assets/img/cluster.svg',
        size: {
          width: 25,
          height: 25,
        },
      },
      label: {
        text: String(count),
        color: '#fff',
        fontWeight: '600',
      },
      position,
    })
  }
}
```

And then I just create an instance in Vue and pass it as a renderer prop
