### ISSUE TITLE
Vite build error

### ISSUE THREAD

**Issue by makroxyz** [diegoazh/gmap-vue#277]
## Describe the bug

running ```npm run build``` on vite gives

Could not resolve './node_modules/.pnpm/core-js@3.21.1/node_modules/core-js/internals/window.js' from node_modules/gmap-vue/dist/esm/main.js
error during build:
Error: Could not resolve './node_modules/.pnpm/core-js@3.21.1/node_modules/core-js/internals/window.js' from node_modules/gmap-vue/dist/esm/main.js
    at error (/home/vagrant/code/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/home/vagrant/code/node_modules/rollup/dist/shared/rollup.js:22508:24)
    at /home/vagrant/code/node_modules/rollup/dist/shared/rollup.js:22471:26

## To reproduce

simply run ```npm run build```

## Expected behavior

Should compile w/o errors

## Current behavior

The error above stops compile

## Desktop (please complete the following information)

 - OS: [Linux]
 - Browser [chrome, firefox]
 - Version [latest]

## Smartphone (please complete the following information)

 - Device: [none]
 - OS: [none]
 - Browser [none]
 - Version [none]

## Additional context

This is the only package that fails

## Versions

- Node: 16.16
- NPM: 8.11
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

Any ideas?

**Comment by makroxyz** [comment]
I solved by myself... need to remove 
```json
define: {
        global: 'window', // fix for packages that support both node and browser
},
```
from vite.config.js

please close.

**Comment by mateusmcordeiro** [comment]
im facing this same problem, but this solution didnt work for me.

**Comment by mateusmcordeiro** [comment]
exactly same error.

My `vite.config.js`:
```
import path from 'path';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue2';
import WindiCSS from 'vite-plugin-windicss';
import postcss from './postcss.config';

const config = defineConfig({
	resolve: {
		alias: {
			path: 'path-browserify',
			'@': `${path.resolve(__dirname, 'src')}`
		}
	},
	define: {
		global: 'window'
	},
	build: {
		minify: true
	},

	plugins: [vue(), WindiCSS()],
	css: {
		postcss
	},
	server: {
		port: 8080
	}
});

export default config;

```

**Comment by arjendejong12** [comment]
This should be forced with the removal of core-js in #273.

**Comment by diegoazh** [comment]
@mateusmcordeiro, was your issue fixed with the last release?

**Comment by diegoazh** [comment]
Migrate to the [new version](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme) of the plugin for Vue v3
