### ISSUE TITLE
Bug: DrawingManager fillColor and strokeColor hdoc

### ISSUE THREAD

**Issue by robertovaldesperez** [diegoazh/gmap-vue#279]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

## Describe the bug

The drawing manager's polygon options are not being used because the fillColor and strokeColor is hardcoded into the setSelection.

`setSelection(shape) {
      this.clearSelection();
      this.selectedShape = shape;
      shape.overlay.setEditable(true);
      shape.overlay.setDraggable(true);
      this.selectedShape.overlay.set('fillColor', '#555');
      this.selectedShape.overlay.set('strokeColor', '#777');
}`

## Desktop (please complete the following information)

 - OS: [Windows 10 Pro]
 - Browser [chrome]
 - Version [latest]

## Smartphone (please complete the following information)

 - Device: [none]
 - OS: [none]
 - Browser [none]
 - Version [none]

## Versions

- Node: v16.13.1
- NPM:
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by davydnorris** [comment]
New drawing manager fixes this - stay tuned

**Comment by robertovaldesperez** [comment]
@davydnorris nice, thanks a lot

**Comment by robertovaldesperez** [comment]
Hi @davydnorris @diegoazh, when do you foresee a new release? Thanks a lot

**Comment by diegoazh** [comment]
Migrate to the [new version](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme) of the plugin for Vue v3

**Comment by robertovaldesperez** [comment]
@diegoazh Does this new version work for vue2?

**Comment by diegoazh** [comment]
> @diegoazh Does this new version work for vue2?

@robertovaldesperez I think no, but I didn't test it on Vue 2, also, Vue 2 is maintained until Decembre of 2023, because of that we stopped the maintenance of this plugin for Vue 2 and I strongly suggest you migrate your code to Vue 3.

**Comment by diegoazh** [comment]
Hi @robertovaldesperez, sorry for being late. You can use the [Cypress folder](https://github.com/diegoazh/gmap-vue/blob/master/packages/v3/cypress/runner/main.js) as an example of how to use it. You can find examples of almost all components inside the [components folder](https://github.com/diegoazh/gmap-vue/tree/master/packages/v3/cypress/runner/components).
