### ISSUE TITLE
Need help on: Using Geocoder with GMap

### ISSUE THREAD

**Issue by jpschutte** [diegoazh/gmap-vue#280]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

## What you try to do

I would like to use the Google Maps Geocoder with the GMap component. I need to be able to use Geocoder within a click event on the GMap component. I'd like when a user clicks on the map, that Geocoder submits the coords and returns the physical address.

## What is the problem

I can't figure out how to load Geocoder as there is no component in the docs.

## What kind of things have you already treated

I have tried something like:

```
mounted () {
    this.$geocoder = new google.maps.Geocoder()
  },

  methods: {
    handleUpdatePosition (position) {
      this.$geocoder.geocode({
        location: {
          lat: position.latitude,
          lng: position.longitude
        }
      }).then(res => console.log('res', res))
    }
  }
```

However, I get an error: `Error in mounted hook (Promise/async): "ReferenceError: google is not defined"`

## Steps to reproduce

Install gmap-vue plugin, load the GmapMap component and try to implement Geocoder.

## Os

- [X] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: 14.17.0
- NPM: 8.1.4
- Yarn:

## Package manager

- [X] NPM
- [ ] Yarn

## Plugin version

- [X]  3.5.3
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by davydnorris** [comment]
Make sure yo check the documentation before submitting a ticket - there's a whole section on this, with examples

[https://diegoazh.github.io/gmap-vue/#accessing-google-maps-api](https://diegoazh.github.io/gmap-vue/#accessing-google-maps-api)
