### ISSUE TITLE
Bug: GoogleMapsCallback is not a function

### ISSUE THREAD

**Issue by joshstrange** [diegoazh/gmap-vue#284]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

## Describe the bug

If you don't have a `GmapMap` component on your page (or if it's not visible/rendered) and you try to use dynamic importing (`googleMapsApiInitializer`) then you might see this error:

```
locations:1 Uncaught (in promise) _.qe {message: 'GoogleMapsCallback is not a function', stack: 'Error\n    at _.qe.captureStackTrace (https://maps/.…es%2Cgeometry&callback=GoogleMapsCallback:235:269', name: 'InvalidValueError'}
```

## To reproduce

1. Initialize the plugin but pass in `dynamicLoad: false,` to the config
2. Call `googleMapsApiInitializer` without a `GmapMap` instance on your page
3. See error

## Expected behavior

I would expect that initializing the plugin should be when it sets `window.GoogleMapsCallback` instead of it apparently being only when you use the `GmapMap` component.

## Current behavior

If you don't use the `GmapMap` component then after Google maps loads it will throw an error (the google maps JS code throws the error) because it can't find `window.GoogleMapsCallback`

```
locations:1 Uncaught (in promise) _.qe {message: 'GoogleMapsCallback is not a function', stack: 'Error\n    at _.qe.captureStackTrace (https://maps/.…es%2Cgeometry&callback=GoogleMapsCallback:235:269', name: 'InvalidValueError'}
```

## Screenshots

N/A

## Desktop (please complete the following information)

 - OS: macOS 12.5.1
 - Browser: Chrome
 - Version: 105.0.5195.102

## Smartphone (please complete the following information)

 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

## Additional context

It would be useful to add something to the docs about this and/or actually register that callback at time of plugin initialization instead of waiting until you load a `GmapMap` component.

## Versions

- Node: 12.22.7
- NPM: 6.14.15
- Yarn: N/A

## Package manager

- [X] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x
- [X] 3.5.4

**Comment by escobarAndre** [comment]
Same here

**Comment by FixMiller** [comment]
same here, node: v16.17.0, npm: 8.19.2

**Comment by diegoazh** [comment]
Maintenance of the plugin for Vue v2 is stopped. Please migrate to the [new version for Vue v3](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme).
