### ISSUE TITLE
Need help on:  Google is not defined triggered by path: google.maps.SymbolPath.CIRCLE in Gmap-vue v3.5.4 icon marker

### ISSUE THREAD

**Issue by Mitchellkohler** [diegoazh/gmap-vue#286]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

## What you try to do
I'm trying to display a circle as an marker on the map with path:  google.maps.SymbolPath.CIRCLE

## What is the problem
Google is not defined triggered by path: google.maps.SymbolPath.CIRCLE in Gmap-vue v3.5.4 icon marker 

The documentation on how to fix this with a promise-lazy function is not that clear to me. https://diegoazh.github.io/gmap-vue/code/utils/factories/promise-lazy.html#functions 

## What kind of things have you already treated

I tried to load an SVG with below code but this also triggered "Google is not defined" 
							  ```
url:require('~/static/images/circle-icon.svg'),
scaledSize: new google.maps.Size(40, 40),
```
## Steps to reproduce

`<template>
		<div id="map-container" class="fullwidth-home-map">
			<gmap-map :center="centerLatLng" :zoom="2" map-type-id="roadmap" scrollwheel="false"  style="height: 620px" > 
				<GmapCluster :zoomOnClick="true" :options="clusterOptions()" >
					<gmap-marker  v-for="(marker, index) in markers" :key="marker.title"  :position="marker.position" :icon="marker.icon" :label="marker.label" :clickable="true" :draggable="false"  @click="openInfoWindow(marker)">
					<gmap-info-window :opened="marker.infoWindowStatus" @closeclick="marker.infoWindowStatus=false">
						<div class="infoBox">
							<div class="map-box">
								<a class="listing-img-container">
									<img :src="marker.image" alt="">
									<div class="listing-item-content">
										<h3>{{marker.title}}</h3>
										<span><small>{{marker.address}}</small></span>
									</div>
								</a>
							</div>
						</div>
					</gmap-info-window>
				</gmap-marker>
			</GmapCluster>	
			</gmap-map>
        </div>
</template>

<script>
import GmapVue from '~/node_modules/gmap-vue'
import { components } from "gmap-vue";

export default {
	components: {
			"gmap-cluster": components.Cluster,
        },
	data(){
		return{
			clusterOptions() {
            return {
                renderer: {
                    render: ({ count, position }) => new google.maps.Marker({
                        label: { text: String(count), color: 'white', fontSize: '10px' },
                        icon: {
				     path: google.maps.SymbolPath.CIRCLE,
				     fillColor: "black",
				     fillOpacity: 1,
				     strokeWeight: 2,
				     strokeColor: '#5e72e4',
				     scale: 20,
				},
		        title: `Cluster of ${count} kitespots`,
                        position,
                        // adjust zIndex to be above other markers
                        zIndex: Number(google.maps.Marker.MAX_ZINDEX) + count,
                    }),
                },
            };
        },	
			centerLatLng: {
				lat : 19.716775,
				lng : -18.997580
			},

			markers :[ 
                            {
								position: {
									lat:  -33.829639905483326, 
									lng:  18.480477471603713,
								},
								icon: {
   							      path: google.maps.SymbolPath.CIRCLE, // This causes the ReferenceError: "google is not defined" 
   							      fillColor: "white",
   							      fillOpacity: 1,
							strokeWeight: 2,
								   		strokeColor: '#5e72e4',
								   		scale: 21,
   							    },
   							    label: {
   							      text: '\ue50d', // codepoint from https://fonts.google.com/icons
   							      fontFamily: 'Material Icons',
   							      color: '#5e72e4',
   							      fontSize: '20px',
   							    },	
								title    : 'Dolphin Beach',
								address  : 'Bishop Avenue, New York',
								image    : require('~/static/images/most-img-2.jpg'),
								infoWindowStatus : false
							},				
                            {
								position: {
									lat:  52.37549882361904, 
									lng:  4.831091990818706,
								},
								icon:{							
									url:require('~/static/images/kitesurfmarker.svg'),},
								title    : 'Tom Restaurant',
								address  : '964 School Street, New York',
								image    : require('~/static/images/most-img-1.jpg'), 
								infoWindowStatus : false
							},
						]
		}
	},
	methods: {
		openInfoWindow(marker){
			marker.infoWindowStatus = true;
		}
	}
};
</script>`
## Os

- [ ] Mac Os X

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v16.0.0
- NPM: 7.10.0
- Yarn: 1.22.19

## Package manager

- [ ] Yarn

## Plugin version

- [ ] 1.4.x

**Comment by Mitchellkohler** [comment]
@davydnorris do you know hot to fix the "Google is not defined error" triggered by path: google.maps.SymbolPath.CIRCLE in Gmap-vue v3.5.4 icon marker ?

**Comment by davydnorris** [comment]
@Mitchellkohler To get to the google API directly, you need to use the built in function getGoogleMapsAPI(), as shown in 
[https://diegoazh.github.io/gmap-vue/#accessing-google-maps-api](https://diegoazh.github.io/gmap-vue/#accessing-google-maps-api)

**Comment by Mitchellkohler** [comment]
Nice, thanks, for the help 😊
