### ISSUE TITLE
Bug: Animation bug while moving map

### ISSUE THREAD

**Issue by henriquetroiano** [diegoazh/gmap-vue#293]
Moving map on maps.google.com:
![ezgif-3-f7b0b6000a](https://user-images.githubusercontent.com/63327237/209562877-aa91818e-26f2-4710-b734-d8e74dfbc1a3.gif)

Moving map with the plugin:
![ezgif-3-c627c875de](https://user-images.githubusercontent.com/63327237/209561309-2ad71cde-1827-48d7-8257-75a3da9d5870.gif)

When moving the map, whatever the place it is, it makes a strage effect at the end. Apparently, the maps is moving correctly but the animation makes confuse

this is reproducible with a fresh vue2 app with fresh example.

**Comment by henriquetroiano** [comment]
At first sight, you think that the map goes back to the old point, but not, it's an effect bug

**Comment by davydnorris** [comment]
Can we see your code? This looks like a prop is being set

**Comment by diegoazh** [comment]
Maintenance of this plugin for Vue v2 is stopped, please migrate to [`@gmap-vue/v3`](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme)
