### ISSUE TITLE
Bug: package version 3.5.4 fails to build, because of missing mixin import

### ISSUE THREAD

**Issue by szattila98** [diegoazh/gmap-vue#296]
## Describe the bug

Some components like cluster-icon, import a mixin with a relative path as you can see in the first screenshot. But the mixin is not there, instead it is in the esm folder, so the path is wrong and there is an error on build.

## To reproduce

1. Search for gmap-vue in node_modules
2. See that the mixin is not there where it should be

## Expected behavior

The mixin should have a correct import path.

## Current behavior

The mixin has a wrong import path and it prevents builds.

## Screenshots

<img width="630" alt="image" src="https://user-images.githubusercontent.com/37137309/234226559-1acfa629-8c5b-45e2-b356-eef809a45b06.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/37137309/234227815-ed6b0e5b-61fb-4e79-9431-1d520660138c.png">

## Desktop (please complete the following information)

 - Does not matter as it is a problem with the package itself

## Smartphone (please complete the following information)

- Does not matter as it is a problem with the package itself

## Additional context

I checked version 3.4.5 and that is still correct.

## Versions

- Does not matter as it is a problem with the package itself

## Package manager

- [X] NPM
- [X] Yarn

## Plugin version

- Does not matter as it is a problem with the package itself

**Comment by diegoazh** [comment]
Do you still need this change? or can you migrate to the new package for Vue v3? [`@gmap-vue/v3`](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme)

**Comment by diegoazh** [comment]
Maintenance of this plugin for Vue v2 is stopped, please migrate to [`@gmap-vue/v3`](https://www.npmjs.com/package/@gmap-vue/v3?activeTab=readme)
