### ISSUE TITLE
Do we have the option to rotate the PNG marker?

### ISSUE THREAD

**Issue by Anjgpt** [diegoazh/gmap-vue#313]
@diegoazh Do we have the option to rotate the PNG marker?
As I'm not able to do this with the below approaches.

"gmap-vue": "^3.5.2",

```
<gmap-marker
        v-for="m, index in markers"
        :position="m.position"
        :icon="{
          url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/info-i_maps.png',
          rotation: 90,
        }"
        :key="index"
      />

```
Or 

Using style transform also not working.
```
<gmap-marker
        v-for="m, index in markers"
        :position="m.position"
        :icon="{
          url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/info-i_maps.png',
        }"
        :style="{ transform: 'rotate(90deg)' }"
        :key="index"
      />
```

If I'm doing this with SVG image it's working but there is slowness as I've lot's of markers.

_Originally posted by @Anjgpt in https://github.com/diegoazh/gmap-vue/issues/135#issuecomment-2022353456_

**Comment by diegoazh** [comment]
could you test our new version v2.0.0? also, you can find the main points on our new documentation site, on the other hand, in this new version we are using the new `AdvancedMarkerElement`, I think with the new improvement you could do the rotation.

**Comment by Anjgpt** [comment]
@diegoazh This new version you are referring v2.0.0 is for Vue 3 project? Will that work with Vue 2 project?

**Comment by Anjgpt** [comment]
I've found the solution for this [here](https://betterprogramming.pub/dynamic-svg-markers-for-google-maps-in-vue-js-7541fa1a54a)
I'm able to plot ~2 lakh customized markers smoothly.

**Comment by diegoazh** [comment]
I'm going to close this issue but, feel free to re-open it if something new happens.
