### ISSUE TITLE
Need help on: gmap-vue not working in safari but fine in chrome

### ISSUE THREAD

**Issue by tronixashutrosh** [diegoazh/gmap-vue#314]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

I'm doing import { getGoogleMapsAPI } from 'gmap-vue';
and using it in my vue project

Explain to us what you are trying to do or what is your goal.

This is working fine in chrome but in safari map is not loading and also no error is appearing in my console

## Steps to reproduce

Just install and us use and in your file
import { getGoogleMapsAPI } from 'gmap-vue';
computed:{
google: getGoogleMapsAPI,
}
mounted: {
 this.infoWindow = new this.google.maps.InfoWindow(
        {
          pixelOffset: {
            width: 0,
            height: -10,
          },
          boxStyle: {
            width: '175px',
          },
        },
      );
      this.orangeDotIcon = {
        url: '/images/orange_dot.png',
        anchor: new this.google.maps.Point(4, 4),
      };
      this.blueDotIcon = {
        url: '/images/blue_dot.png',
        anchor: new this.google.maps.Point(4, 4),
      };
      this.pinkDotIcon = {
        url: '/images/pink_dot.png',
        anchor: new this.google.maps.Point(4, 4),
      };
      }

## Os

- [14.4.1 ] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Versions

- Node: v20.11.1
- NPM: v10.2.4
- Yarn: 1.22.22

## Package manager

- [ ] NPM
- [ ✅ ] Yarn

## Plugin version

"vue": "^2.6.14",
"gmap-vue": "^3.5.2"

**Comment by diegoazh** [comment]
You are using the version of the plugin for Vue 2. This version is no longer maintained because of the EOL of Vue 2.
We strongly recommend moving to Vue 3 and the version of this plugin for Vue 3.
