### ISSUE TITLE
Need help on: 

### ISSUE THREAD

**Issue by Tuhtarov** [diegoazh/gmap-vue#316]
When I try to import the MapLayer type then I get the following error in the console:

Error:   Failed to scan for dependencies from entries:
  ✘ [ERROR] No known conditions for "./components" specifier in "@gmap-vue/v3" package [plugin vite:dep-scan]

    script:~/src/components/desktop/settings/MapPage.vue?id=0:54:7:
      54 │ import '@gmap-vue/v3/components'
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~
         
  This error came from the "onResolve" callback registered here:
    node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({

## Steps to reproduce
Just import some type from v3/components

## Os
- [ ] Linux Ubuntu 22.04

- Node: 20
- NPM: 10

## Plugin version
- [ ] 2.1.0

## I use TS 5.2.2, Vue 3.4 and Vite 5.2.0

Also i have this vite config segment:
``` {
 base: `./`,
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      "@store": fileURLToPath(new URL("./src/app/store", import.meta.url)),
    },
  } 
  }```

And this TS config:
```{
  "compilerOptions": {
  ///
    "paths": {
      "@store/*": ["src/app/store/*"],
      "@service/*": ["src/app/service/*"],
      "@/*": ["src/*"],
    },
    }```

**Comment by diegoazh** [comment]
Hi @Tuhtarov, can you provide a minimum reproduction repo? The repo is very useful to understand what you are trying to do.

Remember that `'@gmap-vue/v3/components'` only export types, not real classes. I never tried to import all types in that way `import '@gmap-vue/v3/components'`, I only imported them individually like the following example `import {Map, Marker} from '@gmap-vue/v3/components'`.

**Comment by Tuhtarov** [comment]
@diegoazh, sorry for the trouble, the problem went away after reinstalling node_modules. Thank you
