### ISSUE TITLE
Bug:  the path_changed event does not work on the GvmPolygon component

### ISSUE THREAD

**Issue by Tuhtarov** [diegoazh/gmap-vue#318]
## Describe the bug
The path_changed event does not work on the GvmPolygon component after changing the coordinates of any point or after adding a new point. At the same time, the polygon itself on the map changes.

## To reproduce
To verify this, just repeat the code of this autotest and add console.log to the beginning of the updateEdited function:
https://github.com/diegoazh/gmap-vue/blob/master/packages/v3/cypress/runner/components/PolygonTest.vue

## Expected behavior
The array of polygon coordinates in the reactive variable should change.

## Screenshots
![image](https://github.com/diegoazh/gmap-vue/assets/76086957/18075a14-64d4-41c8-82ef-4d4cee4d4c7d)
The polygon itself has changed, but the data in the reactive variable has not changed

## Desktop
 - OS: windows 10
 - Browser chrome
 - Version 123.0.6312.123

## Versions
- Node: v20.11.1 
- NPM: 10.2.4 
- VUE: 3.4.21 
- VITE: 5.2.0

## Package manager
- NPM

## Plugin version
- 2.1.0

**Comment by Tuhtarov** [comment]
I’ll also add that the GvmMarker geoposition on the map does not change when the data in the reactive variable in my vue component changes. Initially, the marker appears on the map at the coordinates specified in the variable, but does not change when the variable data is changed.

**Comment by diegoazh** [comment]
Hello @Tuhtarov, first of all, thank you for reporting this issue. I fixed the issues in the new version that was landed a few minutes ago. Please test it and let me know if something else happens.
I'm going to close this issue considering it solved but, feel free to re-open it if you consider that necessary.

**Comment by Tuhtarov** [comment]
Hi @diegoazh. It worked after adding the polygon-key attribute.
Thank you very much for the prompt work and for the cool library! :)
