### ISSUE TITLE
Feature: Please Update the Mraker Component from google.maps.Marker to google.maps.marker.AdvancedMarkerElement

### ISSUE THREAD

**Issue by thismujahid** [diegoazh/gmap-vue#331]
I got an warning in my console:

> As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.

**Comment by diegoazh** [comment]
Hello @thismujahid did you update to the last version of the plugin?

Marker component already use the AdvancedMarkerElement, you can check it [here](https://github.com/diegoazh/gmap-vue/blob/f145d6fe30c26f4cc9ecfd454318189eb1cb267a/packages/v3/src/components/marker-icon.vue#L122C24-L122C45)
