### ISSUE TITLE
Start migration to Vue v3 and typescript

### ISSUE THREAD

**Issue by diegoazh** [diegoazh/gmap-vue#36]
We need to start to plan the migration to Vue 3 before August 2020, following the recommendation of the author in this announcement (https://github.com/vuejs/rfcs/issues/183).

**Comment by bclermont** [comment]
it's really done???

**Comment by ellisgl** [comment]
The bot add the "won't fix" tag...
I having a heck of  time getting the extra services running, since I don't have a good def file.

**Comment by diegoazh** [comment]
@ellisgl thank you.

**Comment by diegoazh** [comment]
Discussion continues on #15
