### ISSUE TITLE
Inefficient loops

### ISSUE THREAD

**Issue by davydnorris** [diegoazh/gmap-vue#42]
https://github.com/diegoazh/gmap-vue/blob/d7afa940ca1f81e4241c058e99c5abb154170840/packages/gmap-vue/src/components-implementation/drawing-manager.js#L54

This should be changed back to 

```
for (opt in options) {
```
This is the fastest way to iterate through properties on an Object:
 - fastest for small numbers of items
 - 'in' loops over non-numeric keys
 - any method that uses a callback to do its work is not as efficient for small numbers

**Comment by davydnorris** [comment]
@diegoazh - some housekeeping

Also this one should be changed back too
https://github.com/diegoazh/gmap-vue/blob/d7afa940ca1f81e4241c058e99c5abb154170840/packages/gmap-vue/src/components-implementation/drawing-manager.js#L153

change this to:
```
for (shape in this.shapes) {
```

This is a true array so 'for', 'while' or 'in' is the most efficient

**Comment by diegoazh** [comment]
@davydnorris, in this case, I don't agree with you, because of this: https://github.com/airbnb/javascript#iterators-and-generators.
Sorry for the boot close your issue.

**Comment by davydnorris** [comment]
OK so you're doing it purely for style reasons because of AirBnB rules - no problem.

**Comment by diegoazh** [comment]
> OK so you're doing it purely for style reasons because of AirBnB rules - no problem.

No, is because of this alert.
<img width="451" alt="Screen Shot 2020-08-03 at 02 30 40" src="https://user-images.githubusercontent.com/10166935/89148945-9baad780-d531-11ea-97a5-ae558044acd6.png">
And In our plugin, this is the target when transpile.
