### ISSUE TITLE
Inconsistent quotes

### ISSUE THREAD

**Issue by davydnorris** [diegoazh/gmap-vue#43]
https://github.com/diegoazh/gmap-vue/blob/d7afa940ca1f81e4241c058e99c5abb154170840/packages/gmap-vue/examples/drawing-manager2.html#L89

All double quotes should be changed back to single quotes to be consistent with the other examples

**Comment by davydnorris** [comment]
@diegoazh some more

**Comment by diegoazh** [comment]
@davydnorris yes I note that was Prettier 🤦🏻‍♂️, sorry for the boot.
I need to add some files that are missing in this repository. Don't worry about quotes, during this week I'm going to migrate to Airbnb rules in Eslint and that will fix the quotes problem.
