### ISSUE TITLE
Lazy Load Google Maps

### ISSUE THREAD

**Issue by Kulcanhez** [diegoazh/gmap-vue#6]
Hello @diegoazh, really thank you for keeping to developing this project!

I'm now developing a website that has a google map at the end of the page. Most of the users probably will not even reach the end of the page, so would be really important to lazy load.

What would be the best way to lazyload it?

Thank you once again!

**Comment by diegoazh** [comment]
Hello @Kulcanhez, first of all, thanks for your question, second of all I will share with you an answer ([https://github.com/xkjyeah/vue-google-maps/issues/595#issuecomment-476459465](https://github.com/xkjyeah/vue-google-maps/issues/595#issuecomment-476459465)) that the owner of `vue2-google-maps` gives to a user that ask for the same feature, please read all threads and I hope that it helps you.

**Comment by Kulcanhez** [comment]
> Hello @Kulcanhez, first of all, thanks for your question, second of all I will share with you an answer ([xkjyeah#595 (comment)](https://github.com/xkjyeah/vue-google-maps/issues/595#issuecomment-476459465)) that the owner of `vue2-google-maps` gives to a user that ask for the same feature, please read all threads and I hope that it helps you.
> Please let me know if that answer answers your question, thanks.

Hello @diegoazh, really thank you for your kindness and help.
I read everything and I tried. I'm still new to Vue so probably I'm doing some noobish thing here. I also tried other things and even I was able to load the Google Maps however it was being loaded in the start and not when it came to the viewport. I took a screenshot from the code I think is correct from the issue you mentioned. Really thank you once again :)
![component](https://user-images.githubusercontent.com/5109593/80861039-dd429280-8c63-11ea-84b7-6de73f87862f.png)
![mainjs](https://user-images.githubusercontent.com/5109593/80861041-e3387380-8c63-11ea-80e9-b9dd04f0a2da.png)
![console](https://user-images.githubusercontent.com/5109593/80861044-ee8b9f00-8c63-11ea-973e-20ac7b1d62ec.jpg)

**Comment by diegoazh** [comment]
I think that your error is because on the second screen you are using an object that wasn't imported

```js
import { loadGmapApi } from 'vue2-google-maps';

export default {
  beforeMount() {
    VueGoogleMaps.loadGmapApi({
      key: 'TOPSECRET',
      libraries: 'places',
    });
  }
}
```
instead of that try to use only that you imported like below

```js
import { loadGmapApi } from 'vue2-google-maps';

export default {
  beforeMount() {
    loadGmapApi({
      key: 'TOPSECRET',
      libraries: 'places',
    });
  }
}
```

Let me know if this solves your problem.

**Comment by Kulcanhez** [comment]
> I think that your error is because on the second screen you are using an object that wasn't imported
> 
> ```js
> import { loadGmapApi } from 'vue2-google-maps';
> 
> export default {
>   beforeMount() {
>     VueGoogleMaps.loadGmapApi({
>       key: 'TOPSECRET',
>       libraries: 'places',
>     });
>   }
> }
> ```
> 
> instead of that try to use only that you imported like below
> 
> ```js
> import { loadGmapApi } from 'vue2-google-maps';
> 
> export default {
>   beforeMount() {
>     loadGmapApi({
>       key: 'TOPSECRET',
>       libraries: 'places',
>     });
>   }
> }
> ```
> 
> Let me know if this solves your problem.

Yes, it makes all the sense. Thank you! Now is working but I noticed that is still being loaded in the header and the map is in the footer. Which is like 400kb that is being loaded unnecessarily :/

**Comment by Kulcanhez** [comment]
I solved using Metominc Contextual Consent. I'm already using their product so it's working amazingly, as it solves the cookie and loading issues :) really thank you for the assistance and love!
