### ISSUE TITLE
getBounds undefined in mounted()

### ISSUE THREAD

**Issue by mouadhkaabachi** [diegoazh/gmap-vue#66]
mounted() {
    this.$nextTick(() => {
      this.$refs.gmap.$mapPromise.then(() => {
        console.log(this.$refs.gmap.$mapObject.getBounds())
      });
    });
  },

**Comment by diegoazh** [comment]
@mouadhkaabachi can you please create a new issue? following the required issue template, thanks a lot

**Comment by diegoazh** [comment]
duplicate #67
