### ISSUE TITLE
getBounds undefined in mounted()

### ISSUE THREAD

**Issue by mouadhkaabachi** [diegoazh/gmap-vue#67]
**Describe the bug**
unnable de get map bounds

**To Reproduce**
```
mounted() {
  this.$nextTick(() => {
    this.$refs.gmap.$mapPromise.then(() => {
    console.log(this.$refs.gmap.$mapObject.getBounds())
    });
  });
},
```
**Expected behavior**
if mounted when I do this.$refs.gmap.$mapObject.getBounds().getNorthEast().lat(); I will get the north_east_latitude

**Current behavior**
getBounds undefined

**Comment by Anjgpt** [comment]
@mouadhkaabachi You can try [this](https://diegoazh.github.io/gmap-vue/#lazy-loading
)
```
async mounted() {
    // if you have a reference of Vue in a `vm` variable
    // the following option should work too
    // await vm.$gmapApiPromiseLazy();

    await this.$gmapApiPromiseLazy();
    this.$refs.gmap.$mapPromise.then(() => {
      console.log(this.$refs.gmap.$mapObject.getBounds())
    });
  }
```

**Comment by mouadhkaabachi** [comment]
it returns undefined also :/

**Comment by diegoazh** [comment]
@mouadhkaabachi please try with the new version 2.0.0 and let me know If the issue persists.

**Comment by stavrzt** [comment]
Checked for "2.0.2" and still "undefined", could you check it, please?

**Comment by diegoazh** [comment]
Ok, @stavrzt I'll take a look as soon as possible. Thanks.

**Comment by diegoazh** [comment]
The problem is that the map is not visible yet when you are calling `getBounds` method, the [official documentation](https://developers.google.com/maps/documentation/javascript/reference/map#Map.getBounds) says:
> If the map is not yet initialized or center and zoom have not been set then the result is undefined.

you can try the following example:

```js
export default {
  // ...
  async mounted() {
    await this.$gmapApiPromiseLazy();

    this.$refs.gmap.$mapObject.addListener('tilesloaded', () => {
      console.log('>>>>>>>>>> getCenter', this.$refs.gmap.$mapObject.getCenter())
      console.log('>>>>>>>>>> getZoom', this.$refs.gmap.$mapObject.getZoom())
      console.log('>>>>>>>>>> getBounds', this.$refs.gmap.$mapObject.getBounds())
    });
  },
  // ...
};
```
among that, I will land a new version that emit a tilesloaded Vue event, in that you could do the following:

```vue
<template>
  <div>
    <GmapMap @tilesloaded="yourMethodToFire" :center="center" :zoom="11" style="width: 100%; height: 500px" ref="gmap">
        ....
    </GmapMap>
  </div>
</template>
```

**Comment by diegoazh** [comment]
Sorry, my bad, currently you can use that option, I mean the `tilesloaded` event is already there

```vue
<template>
  <div>
    <GmapMap @tilesloaded="yourMethodToFire" :center="center" :zoom="11" style="width: 100%; height: 500px" ref="gmap">
        ....
    </GmapMap>
  </div>
</template>
```

**Comment by diegoazh** [comment]
I added this to our documentation, you can see it [here](https://diegoazh.github.io/gmap-vue/guide/map.html#some-tricky-parts)
