### ISSUE TITLE
Need help on: Cloud-Based Map Styling

### ISSUE THREAD

**Issue by alkaitagi** [diegoazh/gmap-vue#70]
# What you try to do

I've read about this new great feature allowing us to customize the map's look. I've created map ID with the style I want and now I need to pass the ```mapId``` parameter to the instantiated map.

https://developers.google.com/maps/documentation/javascript/cloud-based-map-styling#example_app

# What is the problem

Did not find any info about this option in this plugin's documentation. Is it implemented yet? If no, how can I apply the id?

**Comment by diegoazh** [comment]
@alkaitagi try with the new version 2.0.0 and let me know if the issue persist, I will close it but feel free to reopen it if you need.
