### ISSUE TITLE
Feature: Improve documentation

### ISSUE THREAD

**Issue by MrToxy** [diegoazh/gmap-vue#71]
There's a lack of documentation for nearly every component.

There are undocumented events that one can only find by checking the examples page such as `zoom_changed`, `center_changed`, and `idle` for `GmapMap` component for example.

A dedicated page for each component clearly showcasing a list of accepted props and events and what they accept and return would be great as it would make the use of the library a lot easier.

**Comment by diegoazh** [comment]
solved on #72
