### ISSUE TITLE
Feature: Improve documentation. Detail props, events and slots for each component

### ISSUE THREAD

**Issue by MrToxy** [diegoazh/gmap-vue#72]
**Is your feature request related to a problem? Please describe.**
I find the documentation really poor and not helpful in most cases.
There's not a clear showcase of the components accepted props and events, what they accept or what they return.

For example, It took me ages to find that the `GmapMap` has events like `center_changed`, `zoom_changed`, and `idle`, stuff that if properly documented would've saved me a couple of hours of research.

In a library that is event-driven like google maps, its imperative to have good documentation so that we can easily implement intricate features with ease

**Describe the solution you'd like**
I'd like the documentation to feature a page for each available component clearly showcasing every `prop`, `slot` and `event` accepted by the component, what options we can pass and what value we should expect to be returned.
A detailed description of when the events are fired is also a must

**Describe alternatives you've considered**
At this point in time, the only alternative I've found is to actually dig into the source code in order to find some information I need, and even then it's not easy

**Additional context**
No additional context is required

**Comment by diegoazh** [comment]
Hello @MrToxy you are right, I agree with you on all points. I am working on API documentation for the plugin but, how you said, the old structure of the plugin not allow us to generate it automatically.
I am planed to change the structure of the API to get a more intuitive and easy code that we can test with unit tests, e2e tests and generate the API documentation automatically.
At the same time, we are trying to prepare the plugin to work with VueJs v3.0. If you want to collaborate with the planning and contribute to some of these debts, you are welcome.
Thanks for your observations and suggestions.
Regards.

**Comment by MrToxy** [comment]
Hi @diegoazh I'd be more than glad to help

**Comment by adavie1** [comment]
Yo estoy dispuesto ayudar con la documentación

**Comment by diegoazh** [comment]
@adavie1 @MrToxy please review the new documentation, restructure the plugin and prepare the documentation toke me soo much time, I will need help to start a new version of the plugin that works with Vue 3 and composition API if you can help we can try to plan it. Others developers that want and can help are welcome too.
