### ISSUE TITLE
Need help on:  set localization for Map

### ISSUE THREAD

**Issue by stalker3343** [diegoazh/gmap-vue#75]
# What you try to do

I need set localization for Map, and change it dynamically.

# What is the problem

I do not know how to do it

# What kind of things have you already treated

l find google documentation for this 
https://developers.google.com/maps/documentation/javascript/localization
And stackOvwrflow answer, but i'm not sure if this is the right way and that it won't break the plugin
https://stackoverflow.com/questions/7065420/how-can-i-change-the-language-of-google-maps-on-the-run

# Steps to reproduce

No steps for reproduce

## Os

- [ ] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [x] Windows

## Mobile

- [x] iOS
- [x] Android

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [x] 1.4.0
- [ ] 1.2.2
- [ ] 1.2.1
- [ ] 1.2.0
- [ ] 1.0.0

**Comment by diegoazh** [comment]
duplicate #78
