### ISSUE TITLE
Set localization for Map

### ISSUE THREAD

**Issue by stalker3343** [diegoazh/gmap-vue#78]
I need set localization for Map, and change it dynamically.

I do not know how to do it

l find google documentation for this 
https://developers.google.com/maps/documentation/javascript/localization
And stackOvwrflow answer, but i'm not sure if this is the right way and that it won't break the plugin
https://stackoverflow.com/questions/7065420/how-can-i-change-the-language-of-google-maps-on-the-run

No steps for reproduce

**Comment by diegoazh** [comment]
@stalker3343 try the new version 2.0.0 and let me know if it works.

**Comment by diegoazh** [comment]
Do you try to use the `options` prop? you can use it to define Google Maps properties that we don't define as Vue props explicitly. Let me know if that works. Regards.
