### ISSUE TITLE
Access the Polygon to use in containsLocation

### ISSUE THREAD

**Issue by kabugh** [diegoazh/gmap-vue#79]
# What you try to do

Hey, first of all, I'd like to thank you for this awesome plugin!
I'd like to use [`containsLocation`](https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation) and to make it work I need to get the access to Polygon.
# What is the problem
I can't access the Polygon in gmap-vue to pass it as an argument.

# What kind of things have you already treated
I've tried to use $refs to access the polygon like this: 
`<gmap-polygon :paths="paths" ref="polygon"></gmap-polygon>`

I've also tried to create new 'fake' polygon using `gmapApi` like this:
`const polygon = new this.google().maps.Polygon({ paths: this.paths})` 
but it throws an error.

# Steps to reproduce
-

## Os

- [ ] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [x] Windows

## Mobile

- [ ] iOS
- [x] Android

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [x] 1.4.0
- [ ] 1.2.2
- [ ] 1.2.1
- [ ] 1.2.0
- [ ] 1.0.0

**Comment by diegoazh** [comment]
@kabugh please try with the new version 2.0.0 and let me know if it works, on the other hand, apologize for the bot and the delay.

**Comment by diegoazh** [comment]
@kabugh the v2.0.0 or above works as expected? let me know, please. Regards.

**Comment by kabugh** [comment]
@diegoazh hey, sorry, I can't reproduce it anymore. If I have a chance to test it, will let you know :)

**Comment by diegoazh** [comment]
Ok, @kabugh in that case I'll close the issue and if the issue still happened feel free to reopen it.
