### ISSUE TITLE
Bug: clusterClass prop missing on gmap-cluster component + can't disable img

### ISSUE THREAD

**Issue by antoinematyja** [diegoazh/gmap-vue#81]
**Describe the bug**
Hello :) First of all thanks for this library 👍 

I'm trying to use the cluster component like this:
https://googlemaps.github.io/v3-utility-library/packages/markerclustererplus/examples/advanced_example.html
The last cluster style : "Circles (css only)".

To reproduce this I need to set a few things like here :
https://github.com/googlemaps/v3-utility-library/blob/master/packages/markerclustererplus/examples/advanced_example.html#L235

The gmap-cluster component has a `styles` prop, but no `clusterClass` prop. It would be nice to add it.
https://googlemaps.github.io/v3-utility-library/interfaces/_google_markerclustererplus.markerclustereroptions.html#clusterclass

Even with this property, I didn't manage to achieve the same result as the example.
I set the `styles` prop to:
```
      [
        {
          width: 30,
          height: 30,
          className: 'custom-clustericon-1'
        },
        {
          width: 40,
          height: 40,
          className: 'custom-clustericon-2'
        },
        {
          width: 50,
          height: 50,
          className: 'custom-clustericon-3'
        }
      ]
```
(and add css styles)

But the gmap-cluster component stills render a `<img src="undefined">` and won't apply the class. My guess is that a `undefined` url is provided and takes over the `styles`.

**To Reproduce**
Create a map with a gmap-cluster, try to set `styles` prop to this:
```
      [
        {
          width: 30,
          height: 30,
          className: 'custom-clustericon-1'
        },
        {
          width: 40,
          height: 40,
          className: 'custom-clustericon-2'
        },
        {
          width: 50,
          height: 50,
          className: 'custom-clustericon-3'
        }
      ]
```

**Expected behavior**
Cluster should be rendered with `custom-clustericon-*` classes

**Current behavior**
A `<img src="undefined">` is rendered

**Screenshots**
Nope

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 84

**Smartphone (please complete the following information):**

**Additional context**
Nope

## Versions

- Node: 12.8
- NPM: 6.14.4
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [x] 1.4.0
- [ ] 1.2.2
- [ ] 1.2.1
- [ ] 1.2.0
- [ ] 1.0.0

**Comment by diegoazh** [comment]
@antoinematyja try the new version 2.0.0 and let me know if you find any issue there. Thanks and apologize for the bot and the delay.

**Comment by diegoazh** [comment]
@antoinematyja cluster is working properly on the new v2.0.3 please test it. Regards.
