### ISSUE TITLE
Map is not shown on nuxt when running on production mode

### ISSUE THREAD

**Issue by Firman95** [diegoazh/gmap-vue#9]
This is my map
`<gmap-map ref="gmaps" :center="center" map-type-id="terrain" :zoom="12">
      <gmap-marker :position="center" />
    </gmap-map>`

The map is shown when running on dev mode, but not on production mode. There is no error console nor network

**Comment by Firman95** [comment]
I think its because the css is not loaded when in production mode. I copy the map.vue css from the plugin to my component and the map displayed perfectly

**Comment by Firman95** [comment]
nevermind, I think its because of my purgecss config not set properly

**Comment by gizburdt** [comment]
@Firman95 What did you add to fix this? :)

**Comment by rationalthinker1** [comment]
@Firman95 Please tell us.

**Comment by Firman95** [comment]
@rationalthinker1 @gizburdt sorry for the late reply. I use purgecss, and that plugin discard css some of mine and this plugin classes. I just white list all that class from purgecss, and it works
