### ISSUE TITLE
Dealing with password managers

### ISSUE THREAD

**Issue by pjatx** [diegoazh/gmap-vue#93]
Hey there,

So I have the plugin working on my project and it works great. Using it in an ecommerce checkout and running into one issue which I'll describe below. 

The form in question is a simple address form. I have a `<gmap-autocomplete>` component that I'm using to drive the address input UX. 

User clicks into the form, starts typing, autocomplete fires up, they select their address and it fills in all the other fields (address 2, city, state, country, etc) for them. 

The issue I'm running into is handling a password manager. If you tell the password manager to fill out the form, it will insert a value into the autocomplete, but the autocomplete dropdown is never triggered thus leaving the user in limbo. 

Is it possible to emit an event or something similar to force the autocomplete to fire and display the list of potential matches without typing in the field?

**Comment by diegoazh** [comment]
duplicate #94
