### ISSUE TITLE
Need help on: Manually triggering autocomplete dropdown

### ISSUE THREAD

**Issue by pjatx** [diegoazh/gmap-vue#94]
# What you try to do

I have a `<gmap-autocomplete>` component that's a simple address field. When the user clicks into the field and starts typing, the autocomplete options popup below the field, the user selects the place they want and my code fills in all of the other address fields automatically. This works great.

The problem I'm running into is when you try to use a password manager. 

# What is the problem

The password manager fills the `<gmap-autocomplete>`, but it doesn't trigger the autocomplete field options below like if you were to type into it. 

It's not clear how to make the `<gmap-autocomplete>` component display place options based on the value the password manager filled the input with.

# What kind of things have you already treated

I've tried manually triggering some the setPlace event, but that doesn't work. 

# Steps to reproduce

Hard to repro with my current code, but can if this explanation is not enough. Just looking for a way to trigger the autocomplete dropdown without the user typing in the field. 

## Os

- [ ] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [ ] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.0
- [ ] 1.2.2
- [ ] 1.2.1
- [ ] 1.2.0
- [ ] 1.0.0

**Comment by pjatx** [comment]
@diegoazh any chance you can take a look at this? guessing this is simple, but have looked through the source code and can't really figure this out.

**Comment by diegoazh** [comment]
@pjatx can you test the new version 2.0.0 and let me know if the issue persists is very strange the behaviour that you mention in the issue. Thank you, apologise for the bot.

**Comment by diegoazh** [comment]
This behaviour is not something related to the plugin is related to the navigator behaviour.

**Comment by pjatx** [comment]
@diegoazh Apologies, I haven't been working on this project for a while. 

I ended up being able to make it work with the following code fwiw: 

```
          <gmap-autocomplete
            @place_changed="setPlace"
            :options="gmOptions"
            :select-first-on-enter="true"
          >
            <template v-slot:input="slotProps">
              <b-input
                name="address"
                id="shipping-address"
                autocomplete="shipping address-line1"
                size="is-medium"
                type="text"
                ref="input"
                @input="forceFocus"
                v-on:listeners="slotProps.listeners"
                v-on:attrs="slotProps.attrs"
                v-model="address1"
              >
              </b-input>
            </template>
          </gmap-autocomplete>
          
          ...
          
    methods: {
      setPlace(place) {
        const ac = place.address_components.reduce((a, c) => {
          a[c.types[0]] = c.short_name
          return a
        })
  
        this.address1 = ac.short_name + ' ' + ac.route
        this.city = ac.locality
        this.state = ac.administrative_area_level_1
        this.country = ac.country
        this.postal_code = ac.postal_code
  
        this.autoAddress = place.formatted_address
        this.first_name = this.first_name
        this.last_name = this.last_name
      },
      forceFocus() {
        if (this.$refs.input) {
          this.$refs.input.focus()
        }
      },
    }
    ```

**Comment by diegoazh** [comment]
@pjatx nice approach.
